/** Compose Claude's single append-file argument without changing native discovery. */
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { getOverdeckHome } from './paths.js';
import { shellQuote } from './shell-quote.js';
interface ContextConfig {
  harness?: string;
  baseCommand?: string;
  appendSystemPromptFile?: string;
  appendSystemPromptFiles?: string[];
}

export function prepareClaudeContext<T extends ContextConfig>(config: T): {
  config: T;
  lines: string[];
  sources: string[];
} {
  const sources = [
    ...(config.appendSystemPromptFile ? [config.appendSystemPromptFile] : []),
    ...(config.appendSystemPromptFiles ?? []),
  ];
  if ((config.harness ?? 'claude-code') !== 'claude-code') return { config, lines: [], sources };

  // Role commands historically embed this flag. Extract only shell-quoted
  // literal paths generated by roleSystemPromptInjectionSync; reject anything
  // else rather than evaluating shell source to discover an instruction file.
  const roleFiles: string[] = [];
  const baseCommand = config.baseCommand?.replace(
    / --append-system-prompt-file '((?:[^']|'\\''|'"'"')*)'/g,
    (_flag, path: string) => {
      roleFiles.push(path.replace(/'\\''|'"'"'/g, "'"));
      return '';
    },
  );
  if (baseCommand?.includes('--append-system-prompt-file')) {
    throw new Error('Claude role context requires a shell-quoted literal file path.');
  }
  sources.unshift(...roleFiles);
  if (sources.length === 0) return { config, lines: [], sources };
  const bundle = join(getOverdeckHome(), 'context', 'launch', `claude-${randomUUID()}.md`);
  const compose = 'const fs=require("fs"),p=require("path");const [out,...files]=process.argv.slice(1);const body=files.map(f=>"Source: "+f+"\\n\\n"+fs.readFileSync(f,"utf8")).join("\\n\\n---\\n\\n");fs.mkdirSync(p.dirname(out),{recursive:true});const tmp=out+".tmp-"+process.pid;fs.writeFileSync(tmp,body,{mode:384});fs.renameSync(tmp,out)';
  return {
    config: { ...config, baseCommand, appendSystemPromptFile: bundle, appendSystemPromptFiles: [] },
    lines: [`node -e ${shellQuote(compose)} ${shellQuote(bundle)} ${sources.map(shellQuote).join(' ')} || exit $?`],
    sources,
  };
}
