// GENERATED FILE — do not edit by hand.
// Source: the pan CLI command registry via `pan admin commands --json`.
// Regenerate: npm run generate:slash-commands   (drift-gated by scripts/lint-slash-commands.sh)
import type { SlashCommand } from './slashCommandTypes';

export const GENERATED_SLASH_COMMANDS: SlashCommand[] = [
  {
    id: 'pan-init',
    label: 'pan init',
    description: 'Initialize Overdeck (~/.overdeck/)',
    insert: 'pan init',
    category: 'Core',
  },
  {
    id: 'pan-sync',
    label: 'pan sync',
    description: 'Sync skills/agents to ~/.claude/ and render the context layers',
    insert: 'pan sync',
    category: 'Core',
  },
  {
    id: 'pan-context-list',
    label: 'pan context list',
    description: 'Show all three layers\' files',
    insert: 'pan context list',
    category: 'Data',
  },
  {
    id: 'pan-context-edit',
    label: 'pan context edit',
    description: 'Open a context layer in $EDITOR',
    insert: 'pan context edit',
    category: 'Data',
  },
  {
    id: 'pan-context-sync',
    label: 'pan context sync',
    description: 'Render the context layers into harness CLAUDE.md files',
    insert: 'pan context sync',
    category: 'Data',
  },
  {
    id: 'pan-context-diff',
    label: 'pan context diff',
    description: 'Show what each harness would receive after templating',
    insert: 'pan context diff',
    category: 'Data',
  },
  {
    id: 'pan-context-validate',
    label: 'pan context validate',
    description: 'Lint layer templates for unclosed or unknown harness blocks',
    insert: 'pan context validate',
    category: 'Data',
  },
  {
    id: 'pan-context-migrate',
    label: 'pan context migrate',
    description: 'One-shot migration from the deprecated sync.devroot model',
    insert: 'pan context migrate',
    category: 'Data',
  },
  {
    id: 'pan-restore',
    label: 'pan restore',
    description: 'Restore from backup',
    insert: 'pan restore ',
    category: 'Data',
  },
  {
    id: 'pan-backup-list',
    label: 'pan backup list',
    description: 'List all backups',
    insert: 'pan backup list',
    category: 'Data',
  },
  {
    id: 'pan-backup-clean',
    label: 'pan backup clean',
    description: 'Remove old backups',
    insert: 'pan backup clean',
    category: 'Data',
  },
  {
    id: 'pan-skills',
    label: 'pan skills',
    description: 'List and manage skills',
    insert: 'pan skills',
    category: 'Core',
  },
  {
    id: 'pan-issues',
    label: 'pan issues',
    description: 'List and triage work across configured trackers',
    insert: 'pan issues',
    category: 'Lifecycle',
  },
  {
    id: 'pan-show',
    label: 'pan show',
    description: 'Unified lens: shadow state, CV, context, health for one issue',
    insert: 'pan show ',
    category: 'Observation',
  },
  {
    id: 'pan-open',
    label: 'pan open',
    description: 'Open an issue workspace in your preferred editor',
    insert: 'pan open ',
    category: 'Observation',
  },
  {
    id: 'pan-review-pending',
    label: 'pan review pending',
    description: 'List completed work awaiting review',
    insert: 'pan review pending',
    category: 'Review',
  },
  {
    id: 'pan-review-request',
    label: 'pan review request',
    description: 'Request re-review after fixing feedback',
    insert: 'pan review request ',
    category: 'Review',
  },
  {
    id: 'pan-review-reset',
    label: 'pan review reset',
    description: 'Reset review/test/merge cycles (human override)',
    insert: 'pan review reset ',
    category: 'Review',
  },
  {
    id: 'pan-review-abort',
    label: 'pan review abort',
    description: 'Kill all running reviewer sessions and leave the worker idle',
    insert: 'pan review abort ',
    category: 'Review',
  },
  {
    id: 'pan-review-mode',
    label: 'pan review mode',
    description: 'Set per-issue review mode (quick, full, or none)',
    insert: 'pan review mode ',
    category: 'Review',
  },
  {
    id: 'pan-review-scope',
    label: 'pan review scope',
    description: 'Set per-issue re-review scope (all, changed, or blockers) — which convoy reviewers re-run (PAN-1874)',
    insert: 'pan review scope ',
    category: 'Review',
  },
  {
    id: 'pan-review-restart',
    label: 'pan review restart',
    description: 'Kill running reviewers and dispatch fresh review pipeline',
    insert: 'pan review restart ',
    category: 'Review',
  },
  {
    id: 'pan-staffing',
    label: 'pan staffing',
    description: 'Show or set per-issue work-model and swarm overrides',
    insert: 'pan staffing ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-backlog-write-sequence',
    label: 'pan backlog write-sequence',
    description: 'Validate a SequenceDoc JSON file and write it to .pan/backlog/sequence.md (triggers auto-commit)',
    insert: 'pan backlog write-sequence ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-backlog-forecast',
    label: 'pan backlog forecast',
    description: 'Pickup forecast (waves / needs-planning / cohort / stats) from sequence.md + SQLite — no HTTP (sand…',
    insert: 'pan backlog forecast',
    category: 'Lifecycle',
  },
  {
    id: 'pan-plan',
    label: 'pan plan',
    description: 'Planning lifecycle commands',
    insert: 'pan plan ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-plan-finalize',
    label: 'pan plan finalize',
    description: 'Mark the workspace plan as proposed and promote it to canonical state',
    insert: 'pan plan finalize ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-plan-done',
    label: 'pan plan done',
    description: 'Complete planning — promote the xBRIEF and transition the issue to Planned',
    insert: 'pan plan done ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-tell',
    label: 'pan tell',
    description: 'Send message to running agent',
    insert: 'pan tell ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-monitor',
    label: 'pan monitor',
    description: 'Long-running background inbox: drain agent mail to stdout (run inside the agent session; PAN-3015)',
    insert: 'pan monitor ',
    category: 'Observation',
  },
  {
    id: 'pan-inbox',
    label: 'pan inbox',
    description: 'Print full bodies of recent agent mail (unread + read archive); moves nothing',
    insert: 'pan inbox ',
    category: 'Observation',
  },
  {
    id: 'pan-kill',
    label: 'pan kill',
    description: 'Stop one qualified agent, or all agents when given an issue ID (workspace preserved)',
    insert: 'pan kill ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-reset-to-planned',
    label: 'pan reset-to-planned',
    description: 'Return a finalized issue to post-planning without deleting its workspace, plan, commits, or branch',
    insert: 'pan reset-to-planned ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-pause',
    label: 'pan pause',
    description: 'Persistently pause an agent and stop it if running',
    insert: 'pan pause ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-unpause',
    label: 'pan unpause',
    description: 'Clear an agent pause gate without spawning it',
    insert: 'pan unpause ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-untroubled',
    label: 'pan untroubled',
    description: 'Clear an agent troubled gate without spawning it',
    insert: 'pan untroubled ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-fork',
    label: 'pan fork',
    description: 'Summary Fork a conversation — creates new session from a summary of previous work; omit <conv> to f…',
    insert: 'pan fork ',
    category: 'Conversation',
  },
  {
    id: 'pan-handoff',
    label: 'pan handoff',
    description: 'Conversation handoff that spawns a new conversation; omit <conv> (or pass "self") to hand off the c…',
    insert: 'pan handoff ',
    category: 'Conversation',
  },
  {
    id: 'pan-unarchive-conversation',
    label: 'pan unarchive-conversation',
    description: 'Restore an archived conversation by exact name or matching title',
    insert: 'pan unarchive-conversation ',
    category: 'Conversation',
  },
  {
    id: 'pan-resume',
    label: 'pan resume',
    description: 'Resume from saved Claude session',
    insert: 'pan resume ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-recover',
    label: 'pan recover',
    description: 'Recover crashed or stopped agent',
    insert: 'pan recover ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-sync-main',
    label: 'pan sync-main',
    description: 'Merge latest main into workspace feature branch',
    insert: 'pan sync-main ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-done',
    label: 'pan done',
    description: 'Mark work complete, move to review',
    insert: 'pan done ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-approve',
    label: 'pan approve',
    description: '[REMOVED] Use dashboard MERGE button instead',
    insert: 'pan approve ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-reopen',
    label: 'pan reopen',
    description: 'Re-enter the pipeline for a closed/completed/cancelled issue (resets specialist state)',
    insert: 'pan reopen ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-wipe',
    label: 'pan wipe',
    description: 'Destructive: removes workspace files, kills processes, deletes branches, clears review state, and r…',
    insert: 'pan wipe ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-destroy',
    label: 'pan destroy',
    description: 'Alias for workspace destroy: remove the issue workspace worktree and branch',
    insert: 'pan destroy ',
    category: 'Workspace',
  },
  {
    id: 'pan-close',
    label: 'pan close',
    description: 'Verify, clean up, and close issue on tracker',
    insert: 'pan close ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-start',
    label: 'pan start',
    description: 'Create workspace and spawn agent for an issue',
    insert: 'pan start ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-strike',
    label: 'pan strike',
    description: 'Spawn strike agent(s) — implement and push a strike branch for Deacon to land through the verified…',
    insert: 'pan strike ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-strike-ready',
    label: 'pan strike-ready',
    description: 'Persist readiness for a pushed strike branch so Deacon can land it',
    insert: 'pan strike-ready ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-knowledge',
    label: 'pan knowledge',
    description: 'Maintain or open the project OKF bundle',
    insert: 'pan knowledge ',
    category: 'Data',
  },
  {
    id: 'pan-knowledge-open',
    label: 'pan knowledge open',
    description: 'Open the project OKF bundle in the local knowledge viewer',
    insert: 'pan knowledge open',
    category: 'Data',
  },
  {
    id: 'pan-swarm',
    label: 'pan swarm',
    description: 'Start or recover parallel swarm slots for a planned issue',
    insert: 'pan swarm ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-swarm-recover',
    label: 'pan swarm recover',
    description: 'Recover a failed swarm slot',
    insert: 'pan swarm recover ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-swarm-freeze',
    label: 'pan swarm freeze',
    description: 'Freeze swarm coordination for an issue: the Deacon skips it until resume',
    insert: 'pan swarm freeze ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-swarm-resume',
    label: 'pan swarm resume',
    description: 'Resume swarm coordination for a frozen issue on the next Deacon patrol',
    insert: 'pan swarm resume ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-swarm-status',
    label: 'pan swarm status',
    description: 'Read-only reconciled swarm state: per-slot rows, hold state, and capacity',
    insert: 'pan swarm status ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-swarm-stop',
    label: 'pan swarm stop',
    description: 'Freeze swarm coordination, then stop all live slot agents (branches and worktrees preserved)',
    insert: 'pan swarm stop ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-swarm-reset',
    label: 'pan swarm reset',
    description: 'Work-preserving reset: stop slots, push unmerged slot branches to origin, remove slot worktrees/bra…',
    insert: 'pan swarm reset ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-task-next',
    label: 'pan task next',
    description: '',
    insert: 'pan task next ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-task-show',
    label: 'pan task show',
    description: '',
    insert: 'pan task show ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-task-claim',
    label: 'pan task claim',
    description: '',
    insert: 'pan task claim ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-task-done',
    label: 'pan task done',
    description: '',
    insert: 'pan task done ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-task-block',
    label: 'pan task block',
    description: '',
    insert: 'pan task block ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-task-unblock',
    label: 'pan task unblock',
    description: '',
    insert: 'pan task unblock ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-task-cancel',
    label: 'pan task cancel',
    description: '',
    insert: 'pan task cancel ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-workspace-create',
    label: 'pan workspace create',
    description: 'Create workspace for issue',
    insert: 'pan workspace create ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-migrate',
    label: 'pan workspace migrate',
    description: 'Migrate workspace between local and remote (stops+pauses the local agent, commits and pushes all wo…',
    insert: 'pan workspace migrate ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-ssh',
    label: 'pan workspace ssh',
    description: 'SSH into remote workspace VM',
    insert: 'pan workspace ssh ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-sync-auth',
    label: 'pan workspace sync-auth',
    description: 'Sync Claude Code credentials to remote workspace',
    insert: 'pan workspace sync-auth ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-start',
    label: 'pan workspace start',
    description: 'Start a stopped remote workspace',
    insert: 'pan workspace start ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-stop',
    label: 'pan workspace stop',
    description: 'Stop (hibernate) a remote workspace',
    insert: 'pan workspace stop ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-list',
    label: 'pan workspace list',
    description: 'List all workspaces',
    insert: 'pan workspace list',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-destroy',
    label: 'pan workspace destroy',
    description: 'Destroy workspace',
    insert: 'pan workspace destroy ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-render-devcontainer',
    label: 'pan workspace render-devcontainer',
    description: 'Re-render <workspace>/.devcontainer/ from the project compose template',
    insert: 'pan workspace render-devcontainer ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-deep-clean',
    label: 'pan workspace deep-clean',
    description: 'Interactive: git clean -fd against a workspace (preserves protected paths)',
    insert: 'pan workspace deep-clean ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-rebuild',
    label: 'pan workspace rebuild',
    description: 'Tear down, re-render, and restart a single workspace Docker stack',
    insert: 'pan workspace rebuild ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-reap',
    label: 'pan workspace reap',
    description: 'List or remove orphaned unhealthy workspace Docker stacks',
    insert: 'pan workspace reap',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-update',
    label: 'pan workspace update',
    description: 'Update skills/agents/rules in an existing workspace',
    insert: 'pan workspace update ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-use-config',
    label: 'pan workspace use-config',
    description: 'Copy installed Overdeck config into workspace (makes it user settings)',
    insert: 'pan workspace use-config ',
    category: 'Workspace',
  },
  {
    id: 'pan-workspace-add-repo',
    label: 'pan workspace add-repo',
    description: 'Add repositories to a progressive polyrepo workspace',
    insert: 'pan workspace add-repo ',
    category: 'Workspace',
  },
  {
    id: 'pan-test-run',
    label: 'pan test run',
    description: 'Run tests for a project or workspace',
    insert: 'pan test run ',
    category: 'Core',
  },
  {
    id: 'pan-test-list',
    label: 'pan test list',
    description: 'List configured tests for a project',
    insert: 'pan test list ',
    category: 'Core',
  },
  {
    id: 'pan-tts-voices-list',
    label: 'pan tts voices list',
    description: 'List saved TTS voices',
    insert: 'pan tts voices list',
    category: 'Core',
  },
  {
    id: 'pan-tts-voices-show',
    label: 'pan tts voices show',
    description: 'Show saved TTS voice details',
    insert: 'pan tts voices show ',
    category: 'Core',
  },
  {
    id: 'pan-tts-voices-play',
    label: 'pan tts voices play',
    description: 'Speak with a saved TTS voice',
    insert: 'pan tts voices play ',
    category: 'Core',
  },
  {
    id: 'pan-tts-voices-delete',
    label: 'pan tts voices delete',
    description: 'Delete a saved TTS voice',
    insert: 'pan tts voices delete ',
    category: 'Core',
  },
  {
    id: 'pan-tts-voices-set-default',
    label: 'pan tts voices set-default',
    description: 'Set the system TTS voice',
    insert: 'pan tts voices set-default ',
    category: 'Core',
  },
  {
    id: 'pan-tts-voices-map',
    label: 'pan tts voices map',
    description: 'Map a TTS event key to a saved voice',
    insert: 'pan tts voices map ',
    category: 'Core',
  },
  {
    id: 'pan-tts-start',
    label: 'pan tts start',
    description: 'Start the local Qwen TTS daemon',
    insert: 'pan tts start',
    category: 'Core',
  },
  {
    id: 'pan-tts-stop',
    label: 'pan tts stop',
    description: 'Stop the local Qwen TTS daemon',
    insert: 'pan tts stop',
    category: 'Core',
  },
  {
    id: 'pan-tts-status',
    label: 'pan tts status',
    description: 'Show local Qwen TTS daemon status',
    insert: 'pan tts status',
    category: 'Core',
  },
  {
    id: 'pan-tts-restart',
    label: 'pan tts restart',
    description: 'Restart the local Qwen TTS daemon',
    insert: 'pan tts restart',
    category: 'Core',
  },
  {
    id: 'pan-tts-install-systemd',
    label: 'pan tts install-systemd',
    description: 'Install a user systemd unit for the local Qwen TTS daemon',
    insert: 'pan tts install-systemd',
    category: 'Core',
  },
  {
    id: 'pan-tts-test',
    label: 'pan tts test',
    description: 'Speak a test phrase using the configured system (priority) voice',
    insert: 'pan tts test ',
    category: 'Core',
  },
  {
    id: 'pan-release-check',
    label: 'pan release check',
    description: 'Run release preflight checks',
    insert: 'pan release check',
    category: 'Flywheel',
  },
  {
    id: 'pan-release-stable',
    label: 'pan release stable',
    description: 'Create a stable release commit and tag',
    insert: 'pan release stable',
    category: 'Flywheel',
  },
  {
    id: 'pan-release-canary',
    label: 'pan release canary',
    description: 'Create a canary release commit and tag',
    insert: 'pan release canary',
    category: 'Flywheel',
  },
  {
    id: 'pan-release-notes',
    label: 'pan release notes',
    description: 'Draft release notes from git history',
    insert: 'pan release notes ',
    category: 'Flywheel',
  },
  {
    id: 'pan-rollout-status',
    label: 'pan rollout status',
    description: 'Print the release set for an issue (releaseStatus + per-component status)',
    insert: 'pan rollout status ',
    category: 'Flywheel',
  },
  {
    id: 'pan-rollout-retry',
    label: 'pan rollout retry',
    description: 'Re-run the release engine for an issue and print the resulting status',
    insert: 'pan rollout retry ',
    category: 'Flywheel',
  },
  {
    id: 'pan-memory-search',
    label: 'pan memory search',
    description: 'Search memory observations',
    insert: 'pan memory search ',
    category: 'Observation',
  },
  {
    id: 'pan-memory-status',
    label: 'pan memory status',
    description: 'Show current memory status for an issue',
    insert: 'pan memory status ',
    category: 'Observation',
  },
  {
    id: 'pan-memory-reset',
    label: 'pan memory reset',
    description: 'Create a memory reset marker',
    insert: 'pan memory reset ',
    category: 'Observation',
  },
  {
    id: 'pan-memory-summary',
    label: 'pan memory summary',
    description: 'Generate a daily markdown memory summary',
    insert: 'pan memory summary ',
    category: 'Observation',
  },
  {
    id: 'pan-memory-doctor',
    label: 'pan memory doctor',
    description: 'Print memory health, pending counts, and provider configuration',
    insert: 'pan memory doctor',
    category: 'Observation',
  },
  {
    id: 'pan-memory-config',
    label: 'pan memory config',
    description: 'Show memory provider and rollup configuration',
    insert: 'pan memory config',
    category: 'Observation',
  },
  {
    id: 'pan-briefing',
    label: 'pan briefing',
    description: 'Print the live Overdeck session briefing markdown',
    insert: 'pan briefing',
    category: 'Observation',
  },
  {
    id: 'pan-compliance-status',
    label: 'pan compliance status',
    description: 'Show compliance mode and recent compliance misses',
    insert: 'pan compliance status',
    category: 'Observation',
  },
  {
    id: 'pan-registry-tag',
    label: 'pan registry tag',
    description: 'Create or update a feature ownership record for an issue',
    insert: 'pan registry tag ',
    category: 'Data',
  },
  {
    id: 'pan-registry-list',
    label: 'pan registry list',
    description: 'List feature ownership records',
    insert: 'pan registry list',
    category: 'Data',
  },
  {
    id: 'pan-registry-show',
    label: 'pan registry show',
    description: 'Show one feature ownership record',
    insert: 'pan registry show ',
    category: 'Data',
  },
  {
    id: 'pan-orders-create',
    label: 'pan orders create',
    description: 'Create a draft order book',
    insert: 'pan orders create ',
    category: 'Flywheel',
  },
  {
    id: 'pan-orders-list',
    label: 'pan orders list',
    description: 'List order books',
    insert: 'pan orders list',
    category: 'Flywheel',
  },
  {
    id: 'pan-orders-show',
    label: 'pan orders show',
    description: 'Show an order book',
    insert: 'pan orders show ',
    category: 'Flywheel',
  },
  {
    id: 'pan-orders-add',
    label: 'pan orders add',
    description: 'Add issues to an order book',
    insert: 'pan orders add ',
    category: 'Flywheel',
  },
  {
    id: 'pan-orders-remove',
    label: 'pan orders remove',
    description: 'Remove an issue from an order book',
    insert: 'pan orders remove ',
    category: 'Flywheel',
  },
  {
    id: 'pan-orders-move',
    label: 'pan orders move',
    description: 'Move an issue within or between lanes',
    insert: 'pan orders move ',
    category: 'Flywheel',
  },
  {
    id: 'pan-orders-start',
    label: 'pan orders start',
    description: 'Start a Flywheel run bound to an order book',
    insert: 'pan orders start ',
    category: 'Flywheel',
  },
  {
    id: 'pan-docs-query',
    label: 'pan docs query',
    description: 'Query the docs index for relevant snippets',
    insert: 'pan docs query ',
    category: 'Data',
  },
  {
    id: 'pan-docs-reindex',
    label: 'pan docs reindex',
    description: 'Regenerate the docs index from current docs/, skills/, etc.',
    insert: 'pan docs reindex',
    category: 'Data',
  },
  {
    id: 'pan-docs-disable',
    label: 'pan docs disable',
    description: 'Disable docs RAG injection',
    insert: 'pan docs disable',
    category: 'Data',
  },
  {
    id: 'pan-docs-enable',
    label: 'pan docs enable',
    description: 'Re-enable docs RAG injection',
    insert: 'pan docs enable',
    category: 'Data',
  },
  {
    id: 'pan-admin-commands',
    label: 'pan admin commands',
    description: 'List every visible pan command (plumbing; feeds composer autocomplete codegen)',
    insert: 'pan admin commands',
    category: 'Admin',
  },
  {
    id: 'pan-admin-state-migrate',
    label: 'pan admin state migrate',
    description: 'Move permanent state to the orphan overdeck-state branch',
    insert: 'pan admin state migrate ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-state-migrate-xbrief',
    label: 'pan admin state migrate-xbrief',
    description: 'Rename state documents to .xbrief.json and migrate legacy envelopes',
    insert: 'pan admin state migrate-xbrief ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-reconcile-labels',
    label: 'pan admin reconcile-labels',
    description: 'Reconcile pipeline labels from permanent issue truth',
    insert: 'pan admin reconcile-labels',
    category: 'Admin',
  },
  {
    id: 'pan-admin-cloister-status',
    label: 'pan admin cloister status',
    description: 'Show Cloister service status and agent health',
    insert: 'pan admin cloister status',
    category: 'Admin',
  },
  {
    id: 'pan-admin-cloister-start',
    label: 'pan admin cloister start',
    description: 'Start Cloister monitoring service',
    insert: 'pan admin cloister start',
    category: 'Admin',
  },
  {
    id: 'pan-admin-cloister-stop',
    label: 'pan admin cloister stop',
    description: 'Stop Cloister monitoring (agents continue running)',
    insert: 'pan admin cloister stop',
    category: 'Admin',
  },
  {
    id: 'pan-admin-cloister-emergency-stop',
    label: 'pan admin cloister emergency-stop',
    description: 'Emergency stop - kill ALL agents immediately',
    insert: 'pan admin cloister emergency-stop',
    category: 'Admin',
  },
  {
    id: 'pan-admin-cloister-brake',
    label: 'pan admin cloister brake',
    description: 'Emergency brake - trim running work agents down to the concurrency cap (idle-first, resumable)',
    insert: 'pan admin cloister brake',
    category: 'Admin',
  },
  {
    id: 'pan-admin-cloister-freeze',
    label: 'pan admin cloister freeze',
    description: 'Globally pause the Deacon (patrols run but skip all actions); running agents unaffected',
    insert: 'pan admin cloister freeze',
    category: 'Admin',
  },
  {
    id: 'pan-admin-cloister-unfreeze',
    label: 'pan admin cloister unfreeze',
    description: 'Resume the Deacon from a global pause',
    insert: 'pan admin cloister unfreeze',
    category: 'Admin',
  },
  {
    id: 'pan-admin-specialists-list',
    label: 'pan admin specialists list',
    description: 'Show all specialists with their status',
    insert: 'pan admin specialists list',
    category: 'Admin',
  },
  {
    id: 'pan-admin-specialists-wake',
    label: 'pan admin specialists wake',
    description: 'Wake up a specialist agent (for testing/debugging)',
    insert: 'pan admin specialists wake ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-specialists-reset',
    label: 'pan admin specialists reset',
    description: 'Reset a specialist (clear session, start fresh)',
    insert: 'pan admin specialists reset ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-specialists-discovery-ready',
    label: 'pan admin specialists discovery-ready',
    description: 'Signal that the review parent finished shared discovery — forks + launches the convoy (PAN-1862)',
    insert: 'pan admin specialists discovery-ready ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-specialists-done',
    label: 'pan admin specialists done',
    description: 'Signal specialist completion (deterministic status update)',
    insert: 'pan admin specialists done',
    category: 'Admin',
  },
  {
    id: 'pan-admin-specialists-logs',
    label: 'pan admin specialists logs',
    description: 'View specialist run logs',
    insert: 'pan admin specialists logs',
    category: 'Admin',
  },
  {
    id: 'pan-admin-specialists-cleanup-logs',
    label: 'pan admin specialists cleanup-logs',
    description: 'Clean up old specialist logs',
    insert: 'pan admin specialists cleanup-logs',
    category: 'Admin',
  },
  {
    id: 'pan-admin-remote-status',
    label: 'pan admin remote status',
    description: 'Show Fly.io connection and machine status',
    insert: 'pan admin remote status',
    category: 'Admin',
  },
  {
    id: 'pan-admin-remote-init',
    label: 'pan admin remote init',
    description: 'Initialize Fly.io app for workspace machines',
    insert: 'pan admin remote init',
    category: 'Admin',
  },
  {
    id: 'pan-admin-remote-resources',
    label: 'pan admin remote resources',
    description: 'Show RAM/disk usage across VMs',
    insert: 'pan admin remote resources',
    category: 'Admin',
  },
  {
    id: 'pan-admin-remote-setup',
    label: 'pan admin remote setup',
    description: 'Setup Fly.io integration (install flyctl, configure auth)',
    insert: 'pan admin remote setup',
    category: 'Admin',
  },
  {
    id: 'pan-admin-remote-reap',
    label: 'pan admin remote reap',
    description: 'Hand completed remote agents (PAN_REMOTE_DONE) to the review pipeline and stop their machines',
    insert: 'pan admin remote reap',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-snapshot',
    label: 'pan admin db snapshot',
    description: 'Create a database snapshot from an external source',
    insert: 'pan admin db snapshot',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-seed',
    label: 'pan admin db seed',
    description: 'Seed a workspace database with the configured seed file',
    insert: 'pan admin db seed ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-status',
    label: 'pan admin db status',
    description: 'Check database status for a workspace',
    insert: 'pan admin db status ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-clean',
    label: 'pan admin db clean',
    description: 'Clean kubectl/stderr garbage from a database dump file',
    insert: 'pan admin db clean ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-config',
    label: 'pan admin db config',
    description: 'Show database configuration for a project',
    insert: 'pan admin db config ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-rebuild-agents',
    label: 'pan admin db rebuild-agents',
    description: 'Rebuild the SQLite agents table from state.json rollback sources (PAN-1908)',
    insert: 'pan admin db rebuild-agents',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-gc-agents',
    label: 'pan admin db gc-agents',
    description: 'Remove stopped work-agent rows for terminal issues',
    insert: 'pan admin db gc-agents',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-rebuild',
    label: 'pan admin db rebuild',
    description: 'Reconstruct the dashboard cache from git + GitHub sources (PAN-1920)',
    insert: 'pan admin db rebuild',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-backfill-records',
    label: 'pan admin db backfill-records',
    description: 'Backfill per-issue permanent records into the infra repo (PAN-1908)',
    insert: 'pan admin db backfill-records',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-restore-verdicts',
    label: 'pan admin db restore-verdicts',
    description: 'Rebuild review_status verdicts from per-issue records + live GitHub PR state (PAN-1922)',
    insert: 'pan admin db restore-verdicts',
    category: 'Admin',
  },
  {
    id: 'pan-admin-db-reconcile-merges',
    label: 'pan admin db reconcile-merges',
    description: 'Backfill fulfilled merge state from tracked PR and branch ancestry evidence (PAN-2311)',
    insert: 'pan admin db reconcile-merges',
    category: 'Admin',
  },
  {
    id: 'pan-admin-config-shadow',
    label: 'pan admin config shadow',
    description: 'Manage shadow mode settings',
    insert: 'pan admin config shadow',
    category: 'Admin',
  },
  {
    id: 'pan-admin-hooks-install',
    label: 'pan admin hooks install',
    description: 'Configure heartbeat hooks for Claude Code and/or Pi',
    insert: 'pan admin hooks install',
    category: 'Admin',
  },
  {
    id: 'pan-admin-hooks-status',
    label: 'pan admin hooks status',
    description: 'Show installed hook harness support',
    insert: 'pan admin hooks status',
    category: 'Admin',
  },
  {
    id: 'pan-admin-tldr',
    label: 'pan admin tldr',
    description: 'TLDR daemon: status, start, stop, warm',
    insert: 'pan admin tldr ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-fpp',
    label: 'pan admin fpp',
    description: 'FPP hooks: check, push, pop, clear, mail',
    insert: 'pan admin fpp ',
    category: 'Admin',
  },
  {
    id: 'pan-admin-conversations-backfill-titles',
    label: 'pan admin conversations backfill-titles',
    description: 'Backfill titles for conversations stuck on "New conversation"',
    insert: 'pan admin conversations backfill-titles',
    category: 'Admin',
  },
  {
    id: 'pan-admin-tracker-linear-states',
    label: 'pan admin tracker linear-states',
    description: 'Manage Linear workflow states',
    insert: 'pan admin tracker linear-states',
    category: 'Admin',
  },
  {
    id: 'pan-admin-tracker-linear-cleanup',
    label: 'pan admin tracker linear-cleanup',
    description: 'Archive old Linear custom states',
    insert: 'pan admin tracker linear-cleanup',
    category: 'Admin',
  },
  {
    id: 'pan-admin-migrate-config',
    label: 'pan admin migrate-config',
    description: 'One-time migration from settings.json to config.yaml',
    insert: 'pan admin migrate-config',
    category: 'Admin',
  },
  {
    id: 'pan-conversations-scan',
    label: 'pan conversations scan',
    description: 'Scan ~/.claude/projects/ and index discovered sessions',
    insert: 'pan conversations scan ',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-search',
    label: 'pan conversations search',
    description: 'Full-text search across session summaries and tags',
    insert: 'pan conversations search ',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-list',
    label: 'pan conversations list',
    description: 'List discovered sessions with structured filters',
    insert: 'pan conversations list',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-show',
    label: 'pan conversations show',
    description: 'Show detailed information for a session by ID',
    insert: 'pan conversations show ',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-jsonl',
    label: 'pan conversations jsonl',
    description: 'Print the Claude JSONL transcript path for a conversation id (the /conv/<N> number)',
    insert: 'pan conversations jsonl ',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-current',
    label: 'pan conversations current',
    description: 'Print the conversation you are currently running inside (deterministic — no scanning/guessing)',
    insert: 'pan conversations current',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-cost',
    label: 'pan conversations cost',
    description: 'Summarize estimated API costs across discovered sessions',
    insert: 'pan conversations cost',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-embed',
    label: 'pan conversations embed',
    description: 'Generate embeddings for enriched sessions (required for --semantic search)',
    insert: 'pan conversations embed ',
    category: 'Conversation',
  },
  {
    id: 'pan-conversations-enrich',
    label: 'pan conversations enrich',
    description: 'Enrich sessions with AI-generated summaries and tags',
    insert: 'pan conversations enrich ',
    category: 'Conversation',
  },
  {
    id: 'pan-ohmypi-auth-status',
    label: 'pan ohmypi-auth status',
    description: 'Show whether omp\'s openai-codex login is valid (auto-refreshes if possible)',
    insert: 'pan ohmypi-auth status',
    category: 'Core',
  },
  {
    id: 'pan-ohmypi-auth-login',
    label: 'pan ohmypi-auth login',
    description: 'Re-authenticate omp\'s openai-codex login via headless device code',
    insert: 'pan ohmypi-auth login',
    category: 'Core',
  },
  {
    id: 'pan-install',
    label: 'pan install',
    description: 'Install Overdeck prerequisites',
    insert: 'pan install',
    category: 'Core',
  },
  {
    id: 'pan-inspect',
    label: 'pan inspect',
    description: 'Request inspection of a completed xBRIEF item before proceeding to the next',
    insert: 'pan inspect ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-caveman-compress',
    label: 'pan caveman-compress',
    description: 'Compress a static reference doc using caveman-compress (manual use only, never automated)',
    insert: 'pan caveman-compress ',
    category: 'Data',
  },
  {
    id: 'pan-scope-list',
    label: 'pan scope list',
    description: 'List all scope xBRIEFs across registered projects (lifecycle dirs + in-flight worktrees)',
    insert: 'pan scope list',
    category: 'Lifecycle',
  },
  {
    id: 'pan-scope-show',
    label: 'pan scope show',
    description: 'Display xBRIEF plan + items + continue-state summary',
    insert: 'pan scope show ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-scope-propose',
    label: 'pan scope propose',
    description: 'Move xBRIEF to proposed/',
    insert: 'pan scope propose ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-scope-approve',
    label: 'pan scope approve',
    description: 'Move xBRIEF to active/ and set status approved',
    insert: 'pan scope approve ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-scope-complete',
    label: 'pan scope complete',
    description: 'Move xBRIEF to completed/',
    insert: 'pan scope complete ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-scope-cancel',
    label: 'pan scope cancel',
    description: 'Move xBRIEF to cancelled/',
    insert: 'pan scope cancel ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-scope-restore',
    label: 'pan scope restore',
    description: 'Restore xBRIEF from completed/ or cancelled/ to active/',
    insert: 'pan scope restore ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-flywheel-merge-blockers',
    label: 'pan flywheel merge-blockers',
    description: 'PRs that passed review but cannot merge (GitHub-native reasons) — reads SQLite directly, no HTTP (s…',
    insert: 'pan flywheel merge-blockers',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-weights',
    label: 'pan flywheel weights',
    description: 'Weighted substrate bugs by affected v1.0 criterion — reads SQLite directly, no HTTP (sandbox-safe)',
    insert: 'pan flywheel weights',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-start',
    label: 'pan flywheel start',
    description: 'Start the Flywheel orchestrator',
    insert: 'pan flywheel start',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-emit-status',
    label: 'pan flywheel emit-status',
    description: 'Validate and publish a FlywheelStatus JSON snapshot to the local dashboard',
    insert: 'pan flywheel emit-status',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-config',
    label: 'pan flywheel config',
    description: 'Get or set Flywheel autonomy configuration',
    insert: 'pan flywheel config',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-status',
    label: 'pan flywheel status',
    description: 'Show the active Flywheel run status',
    insert: 'pan flywheel status',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-stats',
    label: 'pan flywheel stats',
    description: 'Show Flywheel v1.0 readiness stats',
    insert: 'pan flywheel stats',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-pause',
    label: 'pan flywheel pause',
    description: 'Pause the active Flywheel orchestrator run',
    insert: 'pan flywheel pause',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-resume',
    label: 'pan flywheel resume',
    description: 'Resume the paused Flywheel orchestrator run',
    insert: 'pan flywheel resume',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-report',
    label: 'pan flywheel report',
    description: 'Finalize the active Flywheel run: write report.md, commit FLYWHEEL-STATE.md changes, and clear the…',
    insert: 'pan flywheel report',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-complete',
    label: 'pan flywheel complete',
    description: 'Complete a drained order-book run, write its report and retrospective, then continue mechanically',
    insert: 'pan flywheel complete',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-stop',
    label: 'pan flywheel stop',
    description: 'Stop the Flywheel orchestrator gracefully: kill any live session, write report.md, commit FLYWHEEL-…',
    insert: 'pan flywheel stop',
    category: 'Flywheel',
  },
  {
    id: 'pan-flywheel-abort',
    label: 'pan flywheel abort',
    description: 'Discard the active Flywheel run without writing a report',
    insert: 'pan flywheel abort',
    category: 'Flywheel',
  },
  {
    id: 'pan-merge-cancel',
    label: 'pan merge cancel',
    description: 'Cancel a pending Flywheel auto-merge during its cooldown window',
    insert: 'pan merge cancel ',
    category: 'Review',
  },
  {
    id: 'pan-artifacts-create',
    label: 'pan artifacts create',
    description: 'Validate and publish an HTML artifact',
    insert: 'pan artifacts create ',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-publish',
    label: 'pan artifacts publish',
    description: 'Revalidate and republish an existing artifact when changes are pending',
    insert: 'pan artifacts publish ',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-unshare',
    label: 'pan artifacts unshare',
    description: 'Disable an artifact URL without deleting source, snapshots, or metadata',
    insert: 'pan artifacts unshare ',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-share',
    label: 'pan artifacts share',
    description: 'Share an artifact through an external tunnel',
    insert: 'pan artifacts share ',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-validate',
    label: 'pan artifacts validate',
    description: 'Validate an artifact HTML file',
    insert: 'pan artifacts validate ',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-status',
    label: 'pan artifacts status',
    description: 'Show artifact hash and publication status for a file',
    insert: 'pan artifacts status ',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-list',
    label: 'pan artifacts list',
    description: 'List artifacts',
    insert: 'pan artifacts list',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-url',
    label: 'pan artifacts url',
    description: 'Print the wrapper URL for an artifact file',
    insert: 'pan artifacts url ',
    category: 'Data',
  },
  {
    id: 'pan-artifacts-open',
    label: 'pan artifacts open',
    description: 'Open the wrapper URL for an artifact file',
    insert: 'pan artifacts open ',
    category: 'Data',
  },
  {
    id: 'pan-status',
    label: 'pan status',
    description: 'Show running agents',
    insert: 'pan status',
    category: 'Core',
  },
  {
    id: 'pan-dev',
    label: 'pan dev',
    description: 'Start dashboard in development mode with Vite HMR',
    insert: 'pan dev',
    category: 'Core',
  },
  {
    id: 'pan-up',
    label: 'pan up',
    description: 'Start dashboard (and Traefik if enabled)',
    insert: 'pan up',
    category: 'Core',
  },
  {
    id: 'pan-down',
    label: 'pan down',
    description: 'Stop dashboard (and Traefik if enabled)',
    insert: 'pan down',
    category: 'Core',
  },
  {
    id: 'pan-reload',
    label: 'pan reload',
    description: 'Build Overdeck, then restart the dashboard only after the build succeeds',
    insert: 'pan reload',
    category: 'Core',
  },
  {
    id: 'pan-restart',
    label: 'pan restart',
    description: 'Restart a platform component (default: dashboard only — leaves CLIProxy, Traefik, TLDR running)',
    insert: 'pan restart',
    category: 'Core',
  },
  {
    id: 'pan-project-add',
    label: 'pan project add',
    description: 'Register a project with Overdeck',
    insert: 'pan project add ',
    category: 'Project',
  },
  {
    id: 'pan-project-list',
    label: 'pan project list',
    description: 'List all registered projects',
    insert: 'pan project list',
    category: 'Project',
  },
  {
    id: 'pan-project-show',
    label: 'pan project show',
    description: 'Show details for a specific project',
    insert: 'pan project show ',
    category: 'Project',
  },
  {
    id: 'pan-project-rename',
    label: 'pan project rename',
    description: 'Rename a project\'s display name (the registration key stays unchanged)',
    insert: 'pan project rename ',
    category: 'Project',
  },
  {
    id: 'pan-project-remove',
    label: 'pan project remove',
    description: 'Remove a project from the registry',
    insert: 'pan project remove ',
    category: 'Project',
  },
  {
    id: 'pan-project-init',
    label: 'pan project init',
    description: 'Initialize projects.yaml with example configuration',
    insert: 'pan project init',
    category: 'Project',
  },
  {
    id: 'pan-projects-add',
    label: 'pan projects add',
    description: 'Register a project with Overdeck',
    insert: 'pan projects add ',
    category: 'Project',
  },
  {
    id: 'pan-projects-list',
    label: 'pan projects list',
    description: 'List all registered projects',
    insert: 'pan projects list',
    category: 'Project',
  },
  {
    id: 'pan-projects-show',
    label: 'pan projects show',
    description: 'Show details for a specific project',
    insert: 'pan projects show ',
    category: 'Project',
  },
  {
    id: 'pan-projects-rename',
    label: 'pan projects rename',
    description: 'Rename a project\'s display name (the registration key stays unchanged)',
    insert: 'pan projects rename ',
    category: 'Project',
  },
  {
    id: 'pan-projects-remove',
    label: 'pan projects remove',
    description: 'Remove a project from the registry',
    insert: 'pan projects remove ',
    category: 'Project',
  },
  {
    id: 'pan-projects-init',
    label: 'pan projects init',
    description: 'Initialize projects.yaml with example configuration',
    insert: 'pan projects init',
    category: 'Project',
  },
  {
    id: 'pan-health',
    label: 'pan health',
    description: 'Show runtime health of Overdeck services',
    insert: 'pan health',
    category: 'Observation',
  },
  {
    id: 'pan-doctor',
    label: 'pan doctor',
    description: 'Check system health and dependencies',
    insert: 'pan doctor',
    category: 'Core',
  },
  {
    id: 'pan-resources',
    label: 'pan resources',
    description: 'Show RAM usage by agents, conversations, and system processes',
    insert: 'pan resources',
    category: 'Observation',
  },
  {
    id: 'pan-hygiene',
    label: 'pan hygiene',
    description: 'Audit push, worktree, PR, agent, session, branch, workspace, and disk hygiene',
    insert: 'pan hygiene',
    category: 'CLI',
  },
  {
    id: 'pan-update',
    label: 'pan update',
    description: 'Update Overdeck to latest version',
    insert: 'pan update',
    category: 'CLI',
  },
  {
    id: 'pan-cost-today',
    label: 'pan cost today',
    description: 'Show today\'s cost summary',
    insert: 'pan cost today',
    category: 'Data',
  },
  {
    id: 'pan-cost-week',
    label: 'pan cost week',
    description: 'Show weekly cost summary',
    insert: 'pan cost week',
    category: 'Data',
  },
  {
    id: 'pan-cost-month',
    label: 'pan cost month',
    description: 'Show monthly cost summary',
    insert: 'pan cost month',
    category: 'Data',
  },
  {
    id: 'pan-cost-report',
    label: 'pan cost report',
    description: 'Generate a cost report',
    insert: 'pan cost report',
    category: 'Data',
  },
  {
    id: 'pan-cost-issue',
    label: 'pan cost issue',
    description: 'Show costs for a specific issue',
    insert: 'pan cost issue ',
    category: 'Data',
  },
  {
    id: 'pan-cost-budget-create',
    label: 'pan cost budget create',
    description: 'Create a cost budget',
    insert: 'pan cost budget create ',
    category: 'Data',
  },
  {
    id: 'pan-cost-budget-list',
    label: 'pan cost budget list',
    description: 'List all budgets',
    insert: 'pan cost budget list',
    category: 'Data',
  },
  {
    id: 'pan-cost-budget-check',
    label: 'pan cost budget check',
    description: 'Check budget status',
    insert: 'pan cost budget check ',
    category: 'Data',
  },
  {
    id: 'pan-cost-budget-delete',
    label: 'pan cost budget delete',
    description: 'Delete a budget',
    insert: 'pan cost budget delete ',
    category: 'Data',
  },
  {
    id: 'pan-cost-sync',
    label: 'pan cost sync',
    description: 'Import cost events from per-project WAL files into the local database',
    insert: 'pan cost sync',
    category: 'Data',
  },
  {
    id: 'pan-cost-backfill',
    label: 'pan cost backfill',
    description: 'Reconstruct cost events from stored harness session transcripts',
    insert: 'pan cost backfill',
    category: 'Data',
  },
  {
    id: 'pan-serve',
    label: 'pan serve',
    description: 'Start the dashboard server and open it in the default browser (npx launcher)',
    insert: 'pan serve',
    category: 'CLI',
  },
  {
    id: 'pan-show-cv',
    label: 'pan show --cv',
    description: 'Show agent work history (CV)',
    insert: 'pan show  --cv',
    category: 'Observation',
  },
  {
    id: 'pan-show-context',
    label: 'pan show --context',
    description: 'Show context engineering state',
    insert: 'pan show  --context',
    category: 'Observation',
  },
  {
    id: 'pan-show-health',
    label: 'pan show --health',
    description: 'Show health + heartbeat status',
    insert: 'pan show  --health',
    category: 'Observation',
  },
  {
    id: 'pan-plan-auto-start',
    label: 'pan plan --auto --auto-start',
    description: 'Auto-plan the issue, then auto-start the work agent',
    insert: 'pan plan --auto --auto-start ',
    category: 'Lifecycle',
  },
  {
    id: 'pan-review-reset-session',
    label: 'pan review reset --session',
    description: 'Reset review and clear saved Claude session',
    insert: 'pan review reset  --session',
    category: 'Review',
  },
  {
    id: 'pan-fork-plain',
    label: 'pan fork --plain',
    description: 'Plain fork — copy raw history, skip summary',
    insert: 'pan fork  --plain',
    category: 'Conversation',
  },
  {
    id: 'pan-handoff-model',
    label: 'pan handoff --model',
    description: 'Model for the new conversation',
    insert: 'pan handoff  --model ',
    category: 'Conversation',
  },
  {
    id: 'pan-handoff-harness',
    label: 'pan handoff --harness',
    description: 'Harness for the new conversation (claude-code|pi)',
    insert: 'pan handoff  --harness ',
    category: 'Conversation',
  },
  {
    id: 'pan-handoff-cwd',
    label: 'pan handoff --cwd',
    description: 'Working directory for the new conversation',
    insert: 'pan handoff  --cwd ',
    category: 'Conversation',
  },
];
