/**
 * PAN-3943 WI-1: the Deft skill map, read-only allowlist, and host notice.
 */
import { describe, expect, it } from 'vitest';
import {
  DEFT_HOST_NOTICE,
  DEFT_READONLY_SKILLS,
  DEFT_SKILL_MAP,
  applyDeftHostNotice,
  classifyDeftSkill,
} from '../deft.js';

const DEFT_SKILLS_AT_48E8CBF = [
  'article-review', 'build', 'cost', 'debug', 'decompose', 'design-critique', 'feedback', 'gh-arch', 'gh-slice',
  'glossary', 'interview', 'issue-eval', 'portfolio-priority', 'pre-pr', 'probe', 'product-signal', 'refinement',
  'release', 'review-cycle', 'setup', 'swarm', 'sync', 'triage', 'write-skill', 'xbrief',
];

const REQUIRED_SENTENCES = [
  "This skill is loaded from Overdeck's read-only Deft pack.",
  'Do not run directive init, directive update, directive bootstrap, or deft session:start.',
  'Do not install packages, change git hooks or core.hooksPath, edit AGENTS.md, or write under xbrief/.',
  'Overdeck owns planning (.pan/specs), worktrees, review, and merge.',
  'When a step names a task or deft command that is not installed, skip it and report the result in chat.',
  'Do not write files in the repository unless the operator asks for a file.',
];

// Frontmatter shape of content/skills/deft-directive-glossary/SKILL.md at eltmon/directive@48e8cbf.
const GLOSSARY_SKILL_MD = `---
name: deft-directive-glossary
description: >-
  Extract a DDD-style ubiquitous language glossary from the current
  conversation, flagging ambiguities and proposing canonical terms. Saves to
  UBIQUITOUS_LANGUAGE.md.
triggers:
  - domain model
  - glossary
---
<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->

# Deft Glossary

Extract and formalize domain terminology.
`;

function occurrences(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

describe('DEFT_SKILL_MAP', () => {
  it('classifies every Deft skill at the verified commit', () => {
    expect(Object.keys(DEFT_SKILL_MAP)).toHaveLength(25);
    expect(Object.keys(DEFT_SKILL_MAP).sort()).toEqual(DEFT_SKILLS_AT_48E8CBF);
    for (const entry of Object.values(DEFT_SKILL_MAP)) expect(entry.reason).not.toBe('');
  });

  it('derives the read-only allowlist from the compatible and translated classes', () => {
    expect(DEFT_READONLY_SKILLS).toEqual(['cost', 'debug', 'design-critique', 'gh-arch', 'glossary', 'probe', 'write-skill']);
  });

  it('names an Overdeck equivalent for every conflicting skill', () => {
    const conflicting = Object.values(DEFT_SKILL_MAP).filter((entry) => entry.class === 'conflicting');
    expect(conflicting.length).toBeGreaterThan(0);
    for (const entry of conflicting) expect(entry.overdeck).toMatch(/\S/);
  });

  it('excludes unknown skills as unreviewed', () => {
    expect(classifyDeftSkill('brand-new')).toEqual({ class: 'excluded', reason: 'unreviewed' });
    expect(classifyDeftSkill('constructor')).toEqual({ class: 'excluded', reason: 'unreviewed' });
    expect(classifyDeftSkill('swarm')).toMatchObject({ class: 'conflicting', overdeck: 'pan-swarm' });
  });
});

describe('applyDeftHostNotice', () => {
  it('keeps the host notice within 20 lines', () => {
    expect(DEFT_HOST_NOTICE.split('\n').length).toBeLessThanOrEqual(20);
  });

  it('renames the skill, keeps the frontmatter, and inserts the notice once', () => {
    const once = applyDeftHostNotice(GLOSSARY_SKILL_MD, 'glossary');
    const [, frontmatter, body] = once.split(/^---$/m);

    expect(frontmatter).toContain('\nname: glossary\n');
    expect(frontmatter).not.toContain('deft-directive-glossary');
    expect(frontmatter).toContain('description: >-\n  Extract a DDD-style');
    expect(frontmatter).toContain('triggers:\n  - domain model');
    expect(body.startsWith('\n<!-- overdeck:deft-host-notice v1 -->\n')).toBe(true);
    expect(body).toContain('# Deft Glossary');
    for (const sentence of REQUIRED_SENTENCES) expect(occurrences(once, sentence)).toBe(1);
  });

  it('is idempotent', () => {
    const once = applyDeftHostNotice(GLOSSARY_SKILL_MD, 'glossary');
    expect(applyDeftHostNotice(once, 'glossary')).toBe(once);
  });

  it('adds a name line when the frontmatter has none', () => {
    const out = applyDeftHostNotice('---\ndescription: d\n---\nBody\n', 'probe');
    expect(out.startsWith('---\nname: probe\ndescription: d\n---\n')).toBe(true);
    expect(out).toContain(REQUIRED_SENTENCES[0]);
  });

  it('adds frontmatter when the file has none', () => {
    const out = applyDeftHostNotice('# Probe\n', 'probe');
    expect(out.startsWith('---\nname: probe\n---\n<!-- overdeck:deft-host-notice v1 -->\n')).toBe(true);
    expect(out.endsWith('# Probe\n')).toBe(true);
    expect(applyDeftHostNotice(out, 'probe')).toBe(out);
  });
});
