import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { Effect } from 'effect';
import { isContextOverflowTail } from '../context-overflow.js';
import { getAgentRuntimeStateSync, getAgentState, getAgentStateSync, saveAgentStateSync, type AgentState } from '../agents.js';
import { deliverReviewVerdictFeedback } from './review-verdict-feedback.js';
import { AGENTS_DIR } from '../paths.js';
import { getReviewStatusSync, setReviewStatusSync } from '../review-status.js';
import { logDeaconEventSync } from '../persistent-logger.js';
import { REVIEW_SUB_ROLES, type ReviewSubRole } from './review-monitor.js';
import { capturePane, isPaneDead, killSession, listSessionNames, sessionExists, sessionExistsSync } from '../tmux.js';

const REVIEWER_IDLE_FAILURE_MS = 3 * 60 * 1000;
const REVIEW_REPORTS_PRESENT_NUDGE_COOLDOWN_MS = 60 * 1000;
const reviewReportsPresentNudges = new Map<string, number>();

type DeaconReviewSynthesis = {
  verdict: 'passed' | 'blocked';
  topBlocker: string;
  body: string;
};

function extractMarkdownSection(markdown: string, heading: string): string {
  const pattern = new RegExp(`^##\\s+${heading}\\s*\\r?\\n([\\s\\S]*?)(?=^##\\s+|(?![\\s\\S]))`, 'im');
  return markdown.match(pattern)?.[1]?.trim() ?? '';
}

function findBlockingFindings(markdown: string): string[] {
  const findings = extractMarkdownSection(markdown, 'Findings');
  if (!findings || /^none\.?$/i.test(findings)) return [];

  const blockers: string[] = [];
  const headingPattern = /^###\s*(?:!|⊗)\s+(.+)$/gm;
  let match: RegExpExecArray | null;
  while ((match = headingPattern.exec(findings)) !== null) {
    blockers.push(match[1]!.trim());
  }
  return blockers;
}

export function synthesizeReviewFromReports(opts: {
  issueId: string;
  reviewDir: string;
  reports: ReadonlyArray<{ subRole: ReviewSubRole; path: string; body: string }>;
}): DeaconReviewSynthesis {
  const blockers = opts.reports.flatMap(report =>
    findBlockingFindings(report.body).map(title => ({
      subRole: report.subRole,
      title,
      path: report.path,
    })),
  );
  const verdict: 'passed' | 'blocked' = blockers.length > 0 ? 'blocked' : 'passed';
  const topBlocker = blockers[0] ? `[${blockers[0].subRole}] ${blockers[0].title}` : '';
  const blockerSection = blockers.length > 0
    ? blockers.map(blocker => `### [${blocker.subRole}] ${blocker.title}\nSource: ${blocker.path}`).join('\n\n')
    : 'None';
  const cleanSubRoles = opts.reports
    .filter(report => !blockers.some(blocker => blocker.subRole === report.subRole))
    .map(report => `- ${report.subRole}`)
    .join('\n') || 'None';
  const convoyRows = opts.reports.map(report => {
    const blockingCount = findBlockingFindings(report.body).length;
    return `| ${report.subRole} | ready | ${report.path} | ${blockingCount} |`;
  }).join('\n');

  const body = [
    `# Review Synthesis — ${opts.issueId} — ${new Date().toISOString()}`,
    '',
    `## Verdict: ${verdict === 'passed' ? 'APPROVED' : `CHANGES REQUESTED — ${topBlocker}`}`,
    '',
    '## Context',
    '- Generated by Deacon fallback from completed on-disk reviewer reports.',
    `- Review directory: ${opts.reviewDir}`,
    '',
    '## Convoy Status',
    '| Sub-role | Signal | Output | Blocking findings |',
    '| --- | --- | --- | --- |',
    convoyRows,
    '',
    '## Blocking Findings',
    blockerSection,
    '',
    '## Non-blocking Findings',
    'See individual reviewer reports.',
    '',
    '## Clean Sub-roles',
    cleanSubRoles,
    '',
  ].join('\n');

  return { verdict, topBlocker, body };
}

/**
 * Respawn a convoy reviewer that has gone idle without writing its output.
 *
 * PAN-1806: when a reviewer hits a terminal API error it lands back at an idle
 * TUI prompt and never writes a report. Deacon detects that idle state and,
 * on the first occurrence, kills the stale session and starts a fresh reviewer
 * against the same runId, output path, and context manifest. The retry count is
 * persisted on the fresh agent state so a second idle detection signals failure.
 */
async function respawnIdleReviewer(state: AgentState, agentId: string): Promise<boolean> {
  const outputPath = state.reviewOutputPath;
  const attempt = (state.reviewRetryAttempt ?? 0) + 1;
  logDeaconEventSync(`monitorReviewConvoySignals: ${agentId} idle with no output — respawning reviewer (attempt ${attempt})`);

  try {
    await Effect.runPromise(killSession(agentId));
  } catch (err) {
    logDeaconEventSync(`monitorReviewConvoySignals: failed to kill ${agentId} before respawn: ${err instanceof Error ? err.message : String(err)}`);
  }

  if (!outputPath || !state.reviewSubRole || !state.reviewRunId) {
    logDeaconEventSync(`monitorReviewConvoySignals: cannot respawn ${agentId} — missing output/run/subRole`);
    return false;
  }

  try {
    const { spawnReviewSubRoleForIssue } = await import('./review-agent.js');
    const contextManifestPath = join(dirname(outputPath), 'context.json');
    const result = await Effect.runPromise(
      spawnReviewSubRoleForIssue({
        issueId: state.issueId,
        workspace: state.workspace,
        subRole: state.reviewSubRole as ReviewSubRole,
        runId: state.reviewRunId,
        outputPath,
        contextManifestPath,
        synthesisAgentId: state.reviewSynthesisAgentId,
        model: state.model,
        harness: state.harness,
        allowHost: state.hostOverride ?? false,
      }),
    );

    if (!result.success) {
      logDeaconEventSync(`monitorReviewConvoySignals: respawn of ${agentId} failed: ${result.error ?? result.message}`);
      return false;
    }

    const freshState = getAgentStateSync(agentId);
    if (freshState) {
      freshState.reviewRetryAttempt = attempt;
      saveAgentStateSync(freshState);
    }

    logDeaconEventSync(`monitorReviewConvoySignals: respawned ${agentId} as ${result.sessionId}`);
    return true;
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    logDeaconEventSync(`monitorReviewConvoySignals: respawn of ${agentId} threw: ${errMsg}`);
    return false;
  }
}

async function nudgeSynthesisForCompleteReviewerReports(states: readonly AgentState[]): Promise<string[]> {
  const actions: string[] = [];
  const now = Date.now();
  const synthesisStates = states.filter(state =>
    state.role === 'review'
    && !state.reviewSubRole
    && state.reviewRunId
    && state.workspace
    && state.issueId
  );

  for (const state of synthesisStates) {
    const status = getReviewStatusSync(state.issueId);
    if (!status || status.reviewStatus !== 'reviewing') continue;

    const reviewDir = join(state.workspace, '.pan', 'review', state.reviewRunId!);
    if (existsSync(join(reviewDir, 'synthesis.md'))) continue;

    const startedMs = Date.parse(state.startedAt);
    const readyLines: string[] = [];
    const reports: Array<{ subRole: ReviewSubRole; path: string; body: string }> = [];
    let allReportsPresent = true;
    for (const subRole of REVIEW_SUB_ROLES) {
      const outputPath = join(reviewDir, `${subRole}.md`);
      if (!existsSync(outputPath)) {
        allReportsPresent = false;
        break;
      }
      try {
        const outputMtimeMs = statSync(outputPath).mtimeMs;
        if (Number.isFinite(startedMs) && outputMtimeMs < startedMs) {
          allReportsPresent = false;
          break;
        }
      } catch {
        allReportsPresent = false;
        break;
      }
      try {
        reports.push({ subRole, path: outputPath, body: readFileSync(outputPath, 'utf8') });
      } catch {
        allReportsPresent = false;
        break;
      }
      readyLines.push(`REVIEWER_READY ${subRole} ${outputPath}`);
    }
    if (!allReportsPresent) continue;

    const nudgeKey = `${state.id}:${state.reviewRunId}`;
    const lastNudge = reviewReportsPresentNudges.get(nudgeKey);
    if (lastNudge && now - lastNudge < REVIEW_REPORTS_PRESENT_NUDGE_COOLDOWN_MS) continue;

    const sessionAlive = await Effect.runPromise(sessionExists(state.id)).catch(() => false);
    const paneDead = sessionAlive ? await Effect.runPromise(isPaneDead(state.id)).catch(() => true) : true;
    if (lastNudge || !sessionAlive || paneDead) {
      const synthesis = synthesizeReviewFromReports({
        issueId: state.issueId,
        reviewDir,
        reports,
      });
      writeFileSync(join(reviewDir, 'synthesis.md'), synthesis.body);
      setReviewStatusSync(state.issueId, {
        reviewStatus: synthesis.verdict,
        reviewNotes: synthesis.topBlocker || 'Review approved by Deacon fallback from completed reviewer reports',
      });
      if (synthesis.verdict === 'blocked') {
        await Effect.runPromise(deliverReviewVerdictFeedback({
          issueId: state.issueId,
          verdict: 'blocked',
          notes: synthesis.topBlocker || 'Review blocked by Deacon fallback from completed reviewer reports',
          workspacePath: state.workspace,
          prUrl: status.prUrl,
        }));
      }
      if (sessionAlive) {
        await Effect.runPromise(killSession(state.id)).catch((err) => {
          const errMsg = err instanceof Error ? err.message : String(err);
          logDeaconEventSync(`monitorReviewConvoySignals: failed to kill synthesized parent ${state.id}: ${errMsg}`);
        });
      }
      const action = `Synthesized review for ${state.issueId} from ${REVIEW_SUB_ROLES.length} reviewer reports: ${synthesis.verdict}`;
      actions.push(action);
      logDeaconEventSync(`monitorReviewConvoySignals: ${action}`);
      continue;
    }

    const message = [
      'Deacon fallback: all reviewer report files for this review run are present on disk, but synthesis has not been written yet.',
      'If you have not already synthesized this run, treat these as the missing terminal reviewer signals and proceed now:',
      '',
      ...readyLines,
      '',
      'Read the four reports, write synthesis.md, then signal review status exactly as roles/review.md instructs.',
    ].join('\n');

    try {
      const { messageAgent } = await import('../agents.js');
      await messageAgent(state.id, message);
      reviewReportsPresentNudges.set(nudgeKey, now);
      const action = `Nudged ${state.id} to synthesize from ${REVIEW_SUB_ROLES.length} reviewer reports`;
      actions.push(action);
      logDeaconEventSync(`monitorReviewConvoySignals: ${action}`);
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      logDeaconEventSync(`monitorReviewConvoySignals: failed to nudge ${state.id} for complete reviewer reports: ${errMsg}`);
    }
  }

  return actions;
}

export async function monitorReviewConvoySignals(): Promise<string[]> {
  const actions: string[] = [];
  if (!existsSync(AGENTS_DIR)) return actions;

  let agentDirs: string[];
  try {
    agentDirs = readdirSync(AGENTS_DIR).filter(d => d.startsWith('agent-'));
  } catch {
    return actions;
  }

  const reviewStates: AgentState[] = [];

  for (const agentId of agentDirs) {
    // PAN-1908: use the agents table; fall back to state.json only for legacy dirs.
    const state = await Effect.runPromise(
      getAgentState(agentId).pipe(Effect.catch(() => Effect.succeed(null))),
    ).then((dbState) => dbState ?? getAgentStateSync(agentId));
    if (!state) continue;
    if (state.role !== 'review') continue;
    reviewStates.push(state);
    if (!state.reviewSubRole || !state.reviewSynthesisAgentId) continue;
    if (state.reviewMonitorSignaled) continue;

    const startedMs = Date.parse(state.startedAt);

    // PAN-977: the review sub-role launcher now owns the convoy signal — it
    // signals synthesis on process exit (REVIEWER_READY/FAILED/TIMEOUT) and
    // touches `reviewer-signaled`. When that marker is newer than this run's
    // start, the launcher already signaled and Deacon must not double-signal.
    // Deacon stays the rare backup for the case where the launcher's bash
    // process was SIGKILLed before it could signal.
    const signalMarker = join(AGENTS_DIR, agentId, 'reviewer-signaled');
    if (existsSync(signalMarker)) {
      try {
        if (Number.isFinite(startedMs) && statSync(signalMarker).mtimeMs >= startedMs) continue;
      } catch { /* unreadable marker — fall through to backup signaling */ }
    }

    const outputPath = state.reviewOutputPath;
    let outputWrittenForThisRun = false;
    if (outputPath && existsSync(outputPath)) {
      try {
        const outputMtimeMs = statSync(outputPath).mtimeMs;
        outputWrittenForThisRun = Number.isFinite(startedMs) && outputMtimeMs >= startedMs;
      } catch {
        outputWrittenForThisRun = false;
      }
    }
    const deadlineMs = state.reviewDeadlineAt ? Date.parse(state.reviewDeadlineAt) : Number.NaN;

    // The synthesis agent must be alive to receive any signal.
    const synthesisAlive = await Effect.runPromise(sessionExists(state.reviewSynthesisAgentId));
    if (!synthesisAlive) continue;

    // PAN-1557: convoy reviewers are interactive now — there is no headless
    // launcher process / pid file. Liveness is the reviewer's own tmux session:
    // while it's alive the reviewer is still working (or idling attachably after
    // writing its report); once it's gone the reviewer has crashed or been
    // reaped. The Stop-hook is the primary signal (touches reviewer-signaled +
    // delivers REVIEWER_READY); Deacon is the backup for when that didn't fire.
    const reviewerSessionAlive = (await Effect.runPromise(sessionExists(agentId)).catch(() => false))
      && !(await Effect.runPromise(isPaneDead(agentId)).catch(() => true));

    // Startup grace: give the session time to come up before "gone" reads as death.
    const REVIEWER_STARTUP_GRACE_MS = 90_000;
    const withinStartupGrace = Number.isFinite(startedMs) && (Date.now() - startedMs) < REVIEWER_STARTUP_GRACE_MS;

    // PAN-1806: detect a reviewer that hit a terminal API error and is now
    // idle at its TUI prompt with no report written. The Stop-hook mirror
    // reports 'idle' once the model ends its turn; if that persists while the
    // session is alive and the output file is missing, fail fast rather than
    // wait for the hard deadline. Retry once before signaling failure.
    const runtimeState = getAgentRuntimeStateSync(agentId);
    const runtimeIdleAgeMs =
      runtimeState?.state === 'idle'
        ? Date.now() - new Date(runtimeState.lastActivity).getTime()
        : 0;
    const idleAndNoOutput = reviewerSessionAlive && !outputWrittenForThisRun && runtimeIdleAgeMs > REVIEWER_IDLE_FAILURE_MS;

    // PAN-1818: context-window overflow is deterministic on the same diff/manifest.
    // Capture the pane tail and fast-fail BEFORE the idle-respawn branch so we never
    // burn another cycle respawning a reviewer that will re-overflow. Only check when
    // the reviewer is idle at its prompt — an active reviewer cannot have hit a 400 yet.
    let contextOverflowDetected = false;
    if (!outputWrittenForThisRun && runtimeState?.state === 'idle') {
      const tail = await Effect.runPromise(capturePane(agentId, 100)).catch(() => '');
      contextOverflowDetected = isContextOverflowTail(tail);
    }

    let signal: 'ready' | 'failed' | 'timeout' | null = null;
    let reason = '';
    if (outputWrittenForThisRun) {
      // Report exists for this run but the Stop-hook didn't signal (no fresh
      // marker) — back it up with READY. Safe: the report is on disk.
      signal = 'ready';
    } else if (contextOverflowDetected) {
      signal = 'failed';
      reason = 'context-window overflow (no retry — deterministic)';
    } else if (idleAndNoOutput) {
      const attempt = state.reviewRetryAttempt ?? 0;
      if (attempt < 1 && (await respawnIdleReviewer(state, agentId))) {
        continue;
      }
      signal = 'failed';
      reason = `reviewer idle with no output after terminal API error${attempt >= 1 ? ' (retry exhausted)' : ' (retry failed)'}`;
    } else if (reviewerSessionAlive) {
      // Still working or idling attachably. Only intervene if well past the
      // deadline (genuinely wedged).
      if (Number.isFinite(deadlineMs) && Date.now() >= deadlineMs + REVIEWER_STARTUP_GRACE_MS) {
        signal = 'timeout';
        reason = `reviewer still running past deadline ${state.reviewDeadlineAt}`;
      } else {
        continue;
      }
    } else if (withinStartupGrace) {
      // Session not up yet — too early to call it dead.
      continue;
    } else if (Number.isFinite(deadlineMs) && Date.now() >= deadlineMs) {
      signal = 'timeout';
      reason = `reviewer exceeded deadline ${state.reviewDeadlineAt}`;
    } else {
      // Session gone, no report, before deadline → reviewer crashed or exited
      // before writing a report.
      signal = 'failed';
      reason = 'reviewer session ended before writing a report';
    }

    if (!signal) continue;

    const message = signal === 'ready'
      ? `REVIEWER_READY ${state.reviewSubRole} ${outputPath}`
      : signal === 'timeout'
        ? `REVIEWER_TIMEOUT ${state.reviewSubRole} ${reason}`
        : `REVIEWER_FAILED ${state.reviewSubRole} ${reason}`;

    try {
      const { messageAgent } = await import('../agents.js');
      await messageAgent(state.reviewSynthesisAgentId, message);
      state.reviewMonitorSignaled = signal;
      saveAgentStateSync(state);
      const action = `Signaled ${message} to ${state.reviewSynthesisAgentId}`;
      actions.push(action);
      logDeaconEventSync(`monitorReviewConvoySignals: ${action}`);
      if (signal === 'ready') {
        try {
          const { notifyPipelineSync } = await import('../pipeline-notifier.js');
          notifyPipelineSync({ type: 'reviewer_completed', issueId: state.issueId, role: state.reviewSubRole });
        } catch { /* non-fatal */ }
      } else if (signal === 'timeout') {
        try {
          const { notifyPipelineSync } = await import('../pipeline-notifier.js');
          notifyPipelineSync({
            type: 'reviewer_timed_out',
            issueId: state.issueId,
            role: state.reviewSubRole,
            sessionName: agentId,
            attempt: 1,
            maxRetries: 1,
            willRetry: false,
          });
        } catch { /* non-fatal */ }
      }
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      logDeaconEventSync(`monitorReviewConvoySignals: failed to signal ${state.reviewSynthesisAgentId} for ${agentId}: ${errMsg}`);
    }
  }

  actions.push(...await nudgeSynthesisForCompleteReviewerReports(reviewStates));

  return actions;
}

/**
 * Kill orphaned review sessions whose work agent is no longer running.
 *
 * Covers three naming patterns:
 *   - PAN-1059 convoy: `agent-<issueId>-review-<subRole>` (current)
 *   - Legacy specialist: `specialist-*-review-*` (retired)
 *   - Legacy batch: `review-<issueId>-<timestamp>-<role>` (retired)
 *
 * A session is "orphaned" when the corresponding work-agent session
 * `agent-<issueLower>` does not exist.
 */
export async function cleanupOrphanedReviewSessions(): Promise<string[]> {
  const actions: string[] = [];
  let reviewSessions: string[];
  try {
    const allSessions = await Effect.runPromise(listSessionNames());
    const convoyReviewSessions = allSessions.filter(s => /^agent-.*-review-(?:security|correctness|performance|requirements)$/.test(s));
    const legacyReviewSessions = allSessions.filter(s => /^review-/.test(s));
    const canonicalReviewSessions = allSessions.filter(s => /^specialist-.*-review-/.test(s));
    reviewSessions = [...new Set([...convoyReviewSessions, ...legacyReviewSessions, ...canonicalReviewSessions])];
  } catch {
    return actions;
  }

  logDeaconEventSync(`cleanupOrphanedReviewSessions started: found ${reviewSessions.length} review session(s)`);

  for (const reviewSession of reviewSessions) {
    let issueId: string | null = null;

    // PAN-1059 convoy pattern
    const convoyMatch = reviewSession.match(/^agent-([a-z0-9]+-\d+)-review-(?:security|correctness|performance|requirements)$/);
    if (convoyMatch) {
      issueId = convoyMatch[1].toUpperCase();
    } else {
      // Legacy batch pattern: review-<issueId>-<timestamp>
      const legacyMatch = reviewSession.match(/^review-([A-Za-z0-9]+-\d+)-\d+/);
      if (legacyMatch) {
        issueId = legacyMatch[1].toUpperCase();
      } else {
        // Legacy specialist pattern: specialist-<project>-<issueId>-review-<role>
        const canonicalMatch = reviewSession.match(/^specialist-(.+)-([A-Za-z0-9]+-\d+)-review-[a-z-]+$/);
        if (canonicalMatch) {
          issueId = canonicalMatch[2].toUpperCase();
        }
      }
    }

    if (!issueId) {
      logDeaconEventSync(`cleanupOrphanedReviewSessions: ${reviewSession} skipped — unparseable session name`);
      continue;
    }

    // PAN-1059 convoy sub-reviewers are owned by the synthesis agent
    // (agent-<id>-review), not the work agent. Check synthesis first,
    // then fall back to work agent for legacy review sessions.
    const synthesisAgentSession = `agent-${issueId.toLowerCase()}-review`;
    const workAgentSession = `agent-${issueId.toLowerCase()}`;
    if (sessionExistsSync(synthesisAgentSession)) {
      logDeaconEventSync(`cleanupOrphanedReviewSessions: ${reviewSession} kept — synthesis agent ${synthesisAgentSession} exists`);
      continue;
    }
    if (sessionExistsSync(workAgentSession)) {
      logDeaconEventSync(`cleanupOrphanedReviewSessions: ${reviewSession} kept — work agent ${workAgentSession} exists`);
      continue;
    }

    try {
      await Effect.runPromise(killSession(reviewSession)).catch(() => {});
    } catch (err: unknown) {
      const reason = err instanceof Error ? err.message : String(err);
      logDeaconEventSync(`cleanupOrphanedReviewSessions: error killing ${reviewSession}: ${reason}`);
    }

    const msg = `Killed orphaned ${reviewSession} (synthesis ${synthesisAgentSession} and work ${workAgentSession} not running)`;
    actions.push(msg);
    console.log(`[deacon] ${msg}`);
    logDeaconEventSync(`cleanupOrphanedReviewSessions: ${msg}`);
  }
  if (actions.length > 0) {
    logDeaconEventSync(`cleanupOrphanedReviewSessions completed: killed ${actions.length} orphaned session(s)`);
  } else {
    logDeaconEventSync(`cleanupOrphanedReviewSessions completed: no orphaned sessions found`);
  }

  return actions;
}
