import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { Effect } from 'effect';
import { isContextOverflowTail } from '../context-overflow.js';
import { getAgentRuntimeStateSync, getAgentState, getAgentStateSync, saveAgentStateSync, type AgentState } from '../agents.js';
import { deliverReviewVerdictFeedback } from './review-verdict-feedback.js';
import { findVerdictReport } from './review-verdict-report.js';
import { AGENTS_DIR } from '../paths.js';
import { getReviewStatusSync } from '../review-status.js';
import type { HeadAnchor } from '../git-utils.js';
import { logDeaconEventSync } from '../persistent-logger.js';
import { REVIEW_SUB_ROLES, type ReviewSubRole } from './review-monitor.js';
import { capturePane, isPaneDead, killSession, listSessionNames, listSessions, sessionExists, sessionExistsSync } from '../tmux.js';
import { applyCodexAuthBurnFlag, isCodexAuthRouted, paneShowsCodexAuthBurn } from '../codex-auth.js';
import { extractMarkdownSection, findBlockingFindings } from '../review-findings.js';
import { getAgentEffectiveLastActivityMs } from './agent-idle.js';

const REVIEWER_IDLE_FAILURE_MS = 3 * 60 * 1000;
const REVIEW_REPORTS_PRESENT_NUDGE_COOLDOWN_MS = 60 * 1000;
const reviewReportsPresentNudges = new Map<string, number>();

type DeaconReviewSynthesis = {
  verdict: 'passed' | 'blocked';
  topBlocker: string;
  body: string;
};

export function synthesizeReviewFromReports(opts: {
  issueId: string;
  reviewDir: string;
  reports: ReadonlyArray<{ subRole: ReviewSubRole; path: string; body: string }>;
}): DeaconReviewSynthesis {
  const blockers = opts.reports.flatMap(report =>
    findBlockingFindings(report.body).map(title => ({
      subRole: report.subRole,
      title,
      path: report.path,
    })),
  );
  const verdict: 'passed' | 'blocked' = blockers.length > 0 ? 'blocked' : 'passed';
  const topBlocker = blockers[0] ? `[${blockers[0].subRole}] ${blockers[0].title}` : '';
  const blockerSection = blockers.length > 0
    ? blockers.map(blocker => `### [${blocker.subRole}] ${blocker.title}\nSource: ${blocker.path}`).join('\n\n')
    : 'None';
  const cleanSubRoles = opts.reports
    .filter(report => !blockers.some(blocker => blocker.subRole === report.subRole))
    .map(report => `- ${report.subRole}`)
    .join('\n') || 'None';
  const convoyRows = opts.reports.map(report => {
    const blockingCount = findBlockingFindings(report.body).length;
    return `| ${report.subRole} | ready | ${report.path} | ${blockingCount} |`;
  }).join('\n');

  const body = [
    `# Review Synthesis — ${opts.issueId} — ${new Date().toISOString()}`,
    '',
    `## Verdict: ${verdict === 'passed' ? 'APPROVED' : `CHANGES REQUESTED — ${topBlocker}`}`,
    '',
    '## Context',
    '- Generated by Deacon fallback from completed on-disk reviewer reports.',
    `- Review directory: ${opts.reviewDir}`,
    '',
    '## Convoy Status',
    '| Sub-role | Signal | Output | Blocking findings |',
    '| --- | --- | --- | --- |',
    convoyRows,
    '',
    '## Blocking Findings',
    blockerSection,
    '',
    '## Non-blocking Findings',
    'See individual reviewer reports.',
    '',
    '## Clean Sub-roles',
    cleanSubRoles,
    '',
  ].join('\n');

  return { verdict, topBlocker, body };
}

/**
 * Retry a convoy reviewer that has stopped making progress without writing output.
 *
 * The retry covers terminal API errors, warm-resume kickoffs that never start a
 * turn, and elapsed reviewer deadlines. It preserves the same run/output wiring
 * and persists one shared attempt count so every trigger is bounded together.
 */
async function retryReviewer(state: AgentState, agentId: string, trigger: string): Promise<boolean> {
  const outputPath = state.reviewOutputPath;
  const attempt = (state.reviewRetryAttempt ?? 0) + 1;
  logDeaconEventSync(`monitorReviewConvoySignals: ${agentId} ${trigger} — retrying reviewer (attempt ${attempt})`);

  try {
    await Effect.runPromise(killSession(agentId));
  } catch (err) {
    logDeaconEventSync(`monitorReviewConvoySignals: failed to kill ${agentId} before respawn: ${err instanceof Error ? err.message : String(err)}`);
  }

  if (!outputPath || !state.reviewSubRole || !state.reviewRunId) {
    logDeaconEventSync(`monitorReviewConvoySignals: cannot respawn ${agentId} — missing output/run/subRole`);
    return false;
  }

  try {
    const { spawnReviewSubRoleForIssue } = await import('./review-agent.js');
    const contextManifestPath = join(dirname(outputPath), 'context.json');
    const result = await Effect.runPromise(
      spawnReviewSubRoleForIssue({
        issueId: state.issueId,
        workspace: state.workspace,
        subRole: state.reviewSubRole as ReviewSubRole,
        runId: state.reviewRunId,
        outputPath,
        contextManifestPath,
        synthesisAgentId: state.reviewSynthesisAgentId,
        model: state.model,
        harness: state.harness,
        allowHost: state.hostOverride ?? false,
      }),
    );

    if (!result.success) {
      logDeaconEventSync(`monitorReviewConvoySignals: respawn of ${agentId} failed: ${result.error ?? result.message}`);
      return false;
    }

    const freshState = getAgentStateSync(agentId);
    if (freshState) {
      freshState.reviewRetryAttempt = attempt;
      saveAgentStateSync(freshState);
    }

    logDeaconEventSync(`monitorReviewConvoySignals: respawned ${agentId} as ${result.sessionId}`);
    return true;
  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    logDeaconEventSync(`monitorReviewConvoySignals: respawn of ${agentId} threw: ${errMsg}`);
    return false;
  }
}

export async function nudgeSynthesisForCompleteReviewerReports(states: readonly AgentState[]): Promise<string[]> {
  const actions: string[] = [];
  const now = Date.now();
  const synthesisStates = states.filter(state =>
    state.role === 'review'
    && !state.reviewSubRole
    && state.reviewRunId
    && state.workspace
    && state.issueId
  );

  for (const state of synthesisStates) {
    const status = getReviewStatusSync(state.issueId);
    if (!status || status.reviewStatus !== 'reviewing') continue;

    const reviewDir = join(state.workspace, '.pan', 'review', state.reviewRunId!);
    // A synthesis.md on disk does NOT mean the verdict landed: the parent can
    // die between writing the file and the verdict write door, wedging the issue
    // in 'reviewing' forever (observed 3× on 2026-07-13). Since reviewStatus
    // is still 'reviewing' here (guard above), fall through and land the
    // verdict deterministically instead of skipping.
    const synthesisAlreadyWritten = findVerdictReport(reviewDir) !== null;

    const startedMs = Date.parse(state.startedAt);
    const readyLines: string[] = [];
    const reports: Array<{ subRole: ReviewSubRole; path: string; body: string }> = [];
    let allReportsPresent = true;
    for (const subRole of REVIEW_SUB_ROLES) {
      const outputPath = join(reviewDir, `${subRole}.md`);
      if (!existsSync(outputPath)) {
        allReportsPresent = false;
        break;
      }
      try {
        const outputMtimeMs = statSync(outputPath).mtimeMs;
        if (Number.isFinite(startedMs) && outputMtimeMs < startedMs) {
          allReportsPresent = false;
          break;
        }
      } catch {
        allReportsPresent = false;
        break;
      }
      try {
        reports.push({ subRole, path: outputPath, body: readFileSync(outputPath, 'utf8') });
      } catch {
        allReportsPresent = false;
        break;
      }
      readyLines.push(`REVIEWER_READY ${subRole} ${outputPath}`);
    }
    if (!allReportsPresent) continue;

    const nudgeKey = `${state.id}:${state.reviewRunId}`;
    const lastNudge = reviewReportsPresentNudges.get(nudgeKey);
    if (lastNudge && now - lastNudge < REVIEW_REPORTS_PRESENT_NUDGE_COOLDOWN_MS) continue;

    const sessionAlive = await Effect.runPromise(sessionExists(state.id)).catch(() => false);
    const paneDead = sessionAlive ? await Effect.runPromise(isPaneDead(state.id)).catch(() => true) : true;
    if (synthesisAlreadyWritten || lastNudge || !sessionAlive || paneDead) {
      const synthesis = synthesizeReviewFromReports({
        issueId: state.issueId,
        reviewDir,
        reports,
      });
      writeFileSync(join(reviewDir, 'synthesis.md'), synthesis.body);
      let fallbackHead: HeadAnchor | undefined;
      try {
        // PAN-2948: polyrepo-aware — snapshots sub-repo heads, not the wrapper.
        const { snapshotWorkspaceHeadsPromise } = await import('../git-utils.js');
        fallbackHead = await snapshotWorkspaceHeadsPromise(state.issueId, state.workspace);
      } catch { /* non-fatal — the verdict write door accepts missing evidence. */ }
      const notes = synthesis.topBlocker || 'Review approved by Deacon fallback from completed reviewer reports';
      const { recordReviewVerdict } = await import('./review-verdict-writer.js');
      const outcome = await recordReviewVerdict(state.issueId, {
        verdict: synthesis.verdict,
        notes,
        evidenceHead: fallbackHead,
        ...(synthesis.verdict === 'blocked' && fallbackHead ? { extra: { reviewedAtCommit: fallbackHead } } : {}),
        runId: state.reviewRunId,
        writer: 'fallback',
      });
      if (!outcome.landed) {
        // The verdict of record stays on disk in synthesis.md and the parent stays
        // alive for the PAN-2584 liveness deadline — killing it here would strand a
        // rejected verdict with no session left to re-signal it.
        const rejected = `Deacon fallback verdict for ${state.issueId} was not recorded (${outcome.reason}); left parent ${state.id} alive`;
        actions.push(rejected);
        logDeaconEventSync(`monitorReviewConvoySignals: ${rejected}`);
        continue;
      }
      if (synthesis.verdict === 'blocked') {
        await Effect.runPromise(deliverReviewVerdictFeedback({
          issueId: state.issueId,
          verdict: 'blocked',
          notes,
          workspacePath: state.workspace,
          prUrl: status.prUrl,
          runId: state.reviewRunId,
        }));
      }
      if (sessionAlive) {
        await Effect.runPromise(killSession(state.id)).catch((err) => {
          const errMsg = err instanceof Error ? err.message : String(err);
          logDeaconEventSync(`monitorReviewConvoySignals: failed to kill synthesized parent ${state.id}: ${errMsg}`);
        });
      }
      const action = `Synthesized review for ${state.issueId} from ${REVIEW_SUB_ROLES.length} reviewer reports: ${synthesis.verdict}`;
      actions.push(action);
      logDeaconEventSync(`monitorReviewConvoySignals: ${action}`);
      continue;
    }

    const message = [
      'Deacon fallback: all reviewer report files for this review run are present on disk, but synthesis has not been written yet.',
      'If you have not already synthesized this run, treat these as the missing terminal reviewer signals and proceed now:',
      '',
      ...readyLines,
      '',
      'Read the four reports, write synthesis.md, then signal review status exactly as roles/review.md instructs.',
    ].join('\n');

    try {
      const { messageAgent } = await import('../agents.js');
      await messageAgent(state.id, message);
      reviewReportsPresentNudges.set(nudgeKey, now);
      const action = `Nudged ${state.id} to synthesize from ${REVIEW_SUB_ROLES.length} reviewer reports`;
      actions.push(action);
      logDeaconEventSync(`monitorReviewConvoySignals: ${action}`);
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      logDeaconEventSync(`monitorReviewConvoySignals: failed to nudge ${state.id} for complete reviewer reports: ${errMsg}`);
    }
  }

  return actions;
}

export async function monitorReviewConvoySignals(): Promise<string[]> {
  const actions: string[] = [];
  if (!existsSync(AGENTS_DIR)) return actions;

  let agentDirs: string[];
  try {
    agentDirs = readdirSync(AGENTS_DIR).filter(d => d.startsWith('agent-'));
  } catch {
    return actions;
  }

  // PAN-3549: session-created index for the stale-deadline guard below. One
  // probe up front; if it fails the guard stays off (legacy behavior).
  let sessionCreatedMsByName = new Map<string, number>();
  try {
    const sessions = await Effect.runPromise(listSessions());
    sessionCreatedMsByName = new Map(sessions.map((s) => [s.name, s.created.getTime()]));
  } catch { /* liveness probe failure — guard disabled this sweep */ }

  const reviewStates: AgentState[] = [];

  for (const agentId of agentDirs) {
    // PAN-1908: use the agents table; fall back to state.json only for legacy dirs.
    const state = await Effect.runPromise(
      getAgentState(agentId).pipe(Effect.catch(() => Effect.succeed(null))),
    ).then((dbState) => dbState ?? getAgentStateSync(agentId));
    if (!state) continue;
    if (state.role !== 'review') continue;
    reviewStates.push(state);
    if (!state.reviewSubRole || !state.reviewSynthesisAgentId) continue;
    if (state.reviewMonitorSignaled) continue;

    const startedMs = Date.parse(state.startedAt);

    // PAN-977: the review sub-role launcher now owns the convoy signal — it
    // signals synthesis on process exit (REVIEWER_READY/FAILED/TIMEOUT) and
    // touches `reviewer-signaled`. When that marker is newer than this run's
    // start, the launcher already signaled and Deacon must not double-signal.
    // Deacon stays the rare backup for the case where the launcher's bash
    // process was SIGKILLed before it could signal.
    const signalMarker = join(AGENTS_DIR, agentId, 'reviewer-signaled');
    if (existsSync(signalMarker)) {
      try {
        if (Number.isFinite(startedMs) && statSync(signalMarker).mtimeMs >= startedMs) continue;
      } catch { /* unreadable marker — fall through to backup signaling */ }
    }

    const outputPath = state.reviewOutputPath;
    let outputWrittenForThisRun = false;
    if (outputPath && existsSync(outputPath)) {
      try {
        const outputMtimeMs = statSync(outputPath).mtimeMs;
        outputWrittenForThisRun = Number.isFinite(startedMs) && outputMtimeMs >= startedMs;
      } catch {
        outputWrittenForThisRun = false;
      }
    }
    const deadlineMs = state.reviewDeadlineAt ? Date.parse(state.reviewDeadlineAt) : Number.NaN;

    // The synthesis agent must be alive to receive any signal.
    const synthesisAlive = await Effect.runPromise(sessionExists(state.reviewSynthesisAgentId));
    if (!synthesisAlive) continue;

    // PAN-1557: convoy reviewers are interactive now — there is no headless
    // launcher process / pid file. Liveness is the reviewer's own tmux session:
    // while it's alive the reviewer is still working (or idling attachably after
    // writing its report); once it's gone the reviewer has crashed or been
    // reaped. The Stop-hook is the primary signal (touches reviewer-signaled +
    // delivers REVIEWER_READY); Deacon is the backup for when that didn't fire.
    const reviewerSessionAlive = (await Effect.runPromise(sessionExists(agentId)).catch(() => false))
      && !(await Effect.runPromise(isPaneDead(agentId)).catch(() => true));

    // PAN-3549: a deadline older than the lane's CURRENT tmux session belongs
    // to a dead attempt — run ids are content-derived (head8), so a re-dispatch
    // on the same HEAD inherits the previous attempt's monitor state, and
    // timing out on it kills the fresh lane mid-resume (retryReviewer kills the
    // live session first) while the stale signal replays into the resumed
    // parent as a phantom "infrastructure failure" verdict (PAN-3511,
    // 2026-08-04). The live session is the oracle: clear the stale monitor
    // state through the state door and let the new attempt run.
    if (reviewerSessionAlive && Number.isFinite(deadlineMs)) {
      const sessionCreatedMs = sessionCreatedMsByName.get(agentId);
      if (sessionCreatedMs !== undefined && sessionCreatedMs > deadlineMs) {
        const staleDeadline = state.reviewDeadlineAt;
        delete state.reviewMonitorSignaled;
        delete state.reviewRetryAttempt;
        delete state.reviewDeadlineAt;
        try {
          saveAgentStateSync(state);
        } catch { /* best-effort — the next sweep re-evaluates */ }
        logDeaconEventSync(`monitorReviewConvoySignals: ${agentId} deadline ${staleDeadline} predates its live session — cleared stale monitor state (PAN-3549)`);
        continue;
      }
    }

    // Startup grace: give the session time to come up before "gone" reads as death.
    const REVIEWER_STARTUP_GRACE_MS = 90_000;
    const withinStartupGrace = Number.isFinite(startedMs) && (Date.now() - startedMs) < REVIEWER_STARTUP_GRACE_MS;

    // PAN-1806/PAN-3375: detect both terminal API errors that return to an idle
    // prompt and warm-resume kickoffs that never start a turn. resumeAgent marks
    // the runtime active after delivery, so a swallowed kickoff otherwise leaves
    // a stale active mirror forever. Any real reviewer work refreshes lastActivity;
    // retry once when either mirror is stale and no report exists.
    const runtimeState = getAgentRuntimeStateSync(agentId);
    const runtimeActivityMs = getAgentEffectiveLastActivityMs(agentId)
      ?? (runtimeState?.lastActivity ? Date.parse(runtimeState.lastActivity) : Number.NaN);
    const runtimeActivityAgeMs = Number.isFinite(runtimeActivityMs)
      ? Date.now() - runtimeActivityMs
      : 0;
    const idleAndNoOutput = reviewerSessionAlive
      && !outputWrittenForThisRun
      && runtimeState?.state === 'idle'
      && runtimeActivityAgeMs > REVIEWER_IDLE_FAILURE_MS;
    const staleActiveAndNoOutput = reviewerSessionAlive
      && !outputWrittenForThisRun
      && runtimeState?.state === 'active'
      && runtimeActivityAgeMs > REVIEWER_IDLE_FAILURE_MS;
    const stalledAndNoOutput = idleAndNoOutput || staleActiveAndNoOutput;

    // PAN-1818: context-window overflow is deterministic on the same diff/manifest.
    // Capture the pane tail and fast-fail BEFORE the retry branch so we never
    // burn another cycle on a reviewer that will re-overflow. Check an explicit
    // idle mirror or a stale active mirror whose activity evidence stopped moving.
    let contextOverflowDetected = false;
    if (!outputWrittenForThisRun && (runtimeState?.state === 'idle' || staleActiveAndNoOutput)) {
      const tail = await Effect.runPromise(capturePane(agentId, 100)).catch(() => '');
      contextOverflowDetected = isContextOverflowTail(tail);
      // PAN-2285: a convoy reviewer wedged on a revoked Codex refresh token shows
      // the burn markers in its pane. The idle-no-output path below already fails
      // this reviewer; additionally mark it troubled and persist the burn flag in
      // its agent state (same shape as checkApiErrorAgents) — this monitor runs
      // in the deacon CHILD process, so the flag must reach the dashboard
      // server's banner endpoint and spawn gate through the shared agents table,
      // not module memory.
      //
      // PAN-3528 widened the markers to cover the CLIProxy route, whose 503
      // wrapper text is generic enough to appear in a pane that is not
      // codex-authenticated at all — so only reviewers actually routed through
      // the codex credential family are eligible for the flag.
      const codexRouted = isCodexAuthRouted(state.harness, state.model);
      if (codexRouted && paneShowsCodexAuthBurn(tail) && applyCodexAuthBurnFlag(state)) {
        saveAgentStateSync(state);
        logDeaconEventSync(`review-monitor: ${agentId} marked troubled — Codex refresh token revoked (codex-auth-burned)`);
      }
    }

    let signal: 'ready' | 'failed' | 'timeout' | null = null;
    let reason = '';
    if (outputWrittenForThisRun) {
      // Report exists for this run but the Stop-hook didn't signal (no fresh
      // marker) — back it up with READY. Safe: the report is on disk.
      signal = 'ready';
    } else if (contextOverflowDetected) {
      signal = 'failed';
      reason = 'context-window overflow (no retry — deterministic)';
    } else if (stalledAndNoOutput) {
      const attempt = state.reviewRetryAttempt ?? 0;
      const trigger = staleActiveAndNoOutput
        ? 'warm-resumed but produced no activity or output'
        : 'idle with no output';
      if (attempt < 1 && (await retryReviewer(state, agentId, trigger))) {
        continue;
      }
      signal = 'failed';
      reason = staleActiveAndNoOutput
        ? `reviewer warm-resumed but produced no activity or output${attempt >= 1 ? ' (retry exhausted)' : ' (retry failed)'}`
        : `reviewer idle with no output after terminal API error${attempt >= 1 ? ' (retry exhausted)' : ' (retry failed)'}`;
    } else if (reviewerSessionAlive) {
      // Still working or idling attachably. Only intervene if well past the
      // deadline (genuinely wedged). The first elapsed deadline restarts only
      // this lane; the second produces a terminal timeout for synthesis.
      if (Number.isFinite(deadlineMs) && Date.now() >= deadlineMs + REVIEWER_STARTUP_GRACE_MS) {
        const attempt = state.reviewRetryAttempt ?? 0;
        if (attempt < 1 && (await retryReviewer(state, agentId, `still running past deadline ${state.reviewDeadlineAt}`))) {
          continue;
        }
        signal = 'timeout';
        reason = `reviewer still running past deadline ${state.reviewDeadlineAt}${attempt >= 1 ? ' (retry exhausted)' : ' (retry failed)'}`;
      } else {
        continue;
      }
    } else if (withinStartupGrace) {
      // Session not up yet — too early to call it dead.
      continue;
    } else if (Number.isFinite(deadlineMs) && Date.now() >= deadlineMs) {
      const attempt = state.reviewRetryAttempt ?? 0;
      if (attempt < 1 && (await retryReviewer(state, agentId, `exceeded deadline ${state.reviewDeadlineAt}`))) {
        continue;
      }
      signal = 'timeout';
      reason = `reviewer exceeded deadline ${state.reviewDeadlineAt}${attempt >= 1 ? ' (retry exhausted)' : ' (retry failed)'}`;
    } else {
      // Session gone, no report, before deadline → reviewer crashed or exited
      // before writing a report.
      signal = 'failed';
      reason = 'reviewer session ended before writing a report';
    }

    if (!signal) continue;

    const message = signal === 'ready'
      ? `REVIEWER_READY ${state.reviewSubRole} ${outputPath}`
      : signal === 'timeout'
        ? `REVIEWER_TIMEOUT ${state.reviewSubRole} ${reason}`
        : `REVIEWER_FAILED ${state.reviewSubRole} ${reason}`;

    try {
      const { messageAgent } = await import('../agents.js');
      await messageAgent(state.reviewSynthesisAgentId, message);
      state.reviewMonitorSignaled = signal;
      saveAgentStateSync(state);
      const action = `Signaled ${message} to ${state.reviewSynthesisAgentId}`;
      actions.push(action);
      logDeaconEventSync(`monitorReviewConvoySignals: ${action}`);
      if (signal === 'ready') {
        try {
          const { notifyPipelineSync } = await import('../pipeline-notifier.js');
          notifyPipelineSync({ type: 'reviewer_completed', issueId: state.issueId, role: state.reviewSubRole });
        } catch { /* non-fatal */ }
      } else if (signal === 'timeout') {
        try {
          const { notifyPipelineSync } = await import('../pipeline-notifier.js');
          notifyPipelineSync({
            type: 'reviewer_timed_out',
            issueId: state.issueId,
            role: state.reviewSubRole,
            sessionName: agentId,
            attempt: 1,
            maxRetries: 1,
            willRetry: false,
          });
        } catch { /* non-fatal */ }
      }
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      logDeaconEventSync(`monitorReviewConvoySignals: failed to signal ${state.reviewSynthesisAgentId} for ${agentId}: ${errMsg}`);
    }
  }

  actions.push(...await nudgeSynthesisForCompleteReviewerReports(reviewStates));

  return actions;
}

/**
 * Kill orphaned review sessions whose work agent is no longer running.
 *
 * Covers three naming patterns:
 *   - PAN-1059 convoy: `agent-<issueId>-review-<subRole>` (current)
 *   - Legacy specialist: `specialist-*-review-*` (retired)
 *   - Legacy batch: `review-<issueId>-<timestamp>-<role>` (retired)
 *
 * A session is "orphaned" when the corresponding work-agent session
 * `agent-<issueLower>` does not exist.
 */
export async function cleanupOrphanedReviewSessions(): Promise<string[]> {
  const actions: string[] = [];
  let reviewSessions: string[];
  try {
    const allSessions = await Effect.runPromise(listSessionNames());
    const convoyReviewSessions = allSessions.filter(s => /^agent-.*-review-(?:security|correctness|performance|requirements)$/.test(s));
    const legacyReviewSessions = allSessions.filter(s => /^review-/.test(s));
    const canonicalReviewSessions = allSessions.filter(s => /^specialist-.*-review-/.test(s));
    reviewSessions = [...new Set([...convoyReviewSessions, ...legacyReviewSessions, ...canonicalReviewSessions])];
  } catch {
    return actions;
  }

  logDeaconEventSync(`cleanupOrphanedReviewSessions started: found ${reviewSessions.length} review session(s)`);

  for (const reviewSession of reviewSessions) {
    let issueId: string | null = null;

    // PAN-1059 convoy pattern
    const convoyMatch = reviewSession.match(/^agent-([a-z0-9]+-\d+)-review-(?:security|correctness|performance|requirements)$/);
    if (convoyMatch) {
      issueId = convoyMatch[1].toUpperCase();
    } else {
      // Legacy batch pattern: review-<issueId>-<timestamp>
      const legacyMatch = reviewSession.match(/^review-([A-Za-z0-9]+-\d+)-\d+/);
      if (legacyMatch) {
        issueId = legacyMatch[1].toUpperCase();
      } else {
        // Legacy specialist pattern: specialist-<project>-<issueId>-review-<role>
        const canonicalMatch = reviewSession.match(/^specialist-(.+)-([A-Za-z0-9]+-\d+)-review-[a-z-]+$/);
        if (canonicalMatch) {
          issueId = canonicalMatch[2].toUpperCase();
        }
      }
    }

    if (!issueId) {
      logDeaconEventSync(`cleanupOrphanedReviewSessions: ${reviewSession} skipped — unparseable session name`);
      continue;
    }

    // PAN-1059 convoy sub-reviewers are owned by the synthesis agent
    // (agent-<id>-review), not the work agent. Check synthesis first,
    // then fall back to work agent for legacy review sessions.
    const synthesisAgentSession = `agent-${issueId.toLowerCase()}-review`;
    const workAgentSession = `agent-${issueId.toLowerCase()}`;
    if (sessionExistsSync(synthesisAgentSession)) {
      logDeaconEventSync(`cleanupOrphanedReviewSessions: ${reviewSession} kept — synthesis agent ${synthesisAgentSession} exists`);
      continue;
    }
    if (sessionExistsSync(workAgentSession)) {
      logDeaconEventSync(`cleanupOrphanedReviewSessions: ${reviewSession} kept — work agent ${workAgentSession} exists`);
      continue;
    }

    try {
      await Effect.runPromise(killSession(reviewSession)).catch(() => {});
    } catch (err: unknown) {
      const reason = err instanceof Error ? err.message : String(err);
      logDeaconEventSync(`cleanupOrphanedReviewSessions: error killing ${reviewSession}: ${reason}`);
    }

    const msg = `Killed orphaned ${reviewSession} (synthesis ${synthesisAgentSession} and work ${workAgentSession} not running)`;
    actions.push(msg);
    console.log(`[deacon] ${msg}`);
    logDeaconEventSync(`cleanupOrphanedReviewSessions: ${msg}`);
  }
  if (actions.length > 0) {
    logDeaconEventSync(`cleanupOrphanedReviewSessions completed: killed ${actions.length} orphaned session(s)`);
  } else {
    logDeaconEventSync(`cleanupOrphanedReviewSessions completed: no orphaned sessions found`);
  }

  return actions;
}


/**
 * PAN-2584: liveness WATCH for the review PARENT (synthesis/self-review).
 *
 * ─── OBSERVABILITY ONLY — OPERATOR DIRECTIVE (2026-08-05) ───────────────────
 * This check must NEVER kill, stop, or respawn a parent again. On 2026-08-05
 * it killed the PAN-3511 parent two hours after that parent had recorded a
 * real verdict, because its "no terminal verdict" read used only the runtime
 * row — the plane that was losing verdicts that night. A past-deadline parent
 * now produces a needs-you escalation with the evidence, and the operator (or
 * a deliberately invoked door) decides whether a respawn is warranted.
 * ───────────────────────────────────────────────────────────────────────────
 *
 * The verdict check reads the verdict OF RECORD first (the synthesis artifact
 * via findVerdictReport — PAN-3511's contract), then the runtime row; a
 * terminal verdict in either plane means the parent is warm-idle by design
 * and is skipped. The deadline is explicit (`reviewDeadlineAt`, armed at
 * spawn/resume) with an implicit fallback from the last (re)start for parents
 * predating the arming code.
 */
export async function checkStalledReviewParents(): Promise<string[]> {
  const actions: string[] = [];
  try {
    const { listAgentStates } = await import('../agents.js');
    const { PARENT_REVIEW_TIMEOUT_MS } = await import('./review-agent.js');
    const states = listAgentStates();
    const now = Date.now();
    for (const state of states) {
      if (state.role !== 'review' || state.reviewSubRole || !state.issueId) continue;
      if (state.status !== 'running') continue;
      const armedMs = state.reviewDeadlineAt ? Date.parse(state.reviewDeadlineAt) : Number.NaN;
      const startedMs = Date.parse(state.lastResumeAt ?? state.startedAt);
      const deadlineMs = Number.isFinite(armedMs)
        ? armedMs
        : Number.isFinite(startedMs)
          ? startedMs + PARENT_REVIEW_TIMEOUT_MS
          : Number.NaN;
      if (!Number.isFinite(deadlineMs) || now < deadlineMs) continue;

      // Verdict-of-record first (PAN-3511's contract): the synthesis artifact
      // cannot lose a verdict; the runtime row can (and did, 2026-08-05). A
      // terminal verdict in EITHER plane means warm-idle by design — skip.
      if (hasTerminalVerdictOfRecord(state)) continue;
      const reviewStatus = getReviewStatusSync(state.issueId)?.reviewStatus;
      if (reviewStatus === 'passed' || reviewStatus === 'blocked' || reviewStatus === 'failed') continue;

      // Escalate once per deadline epoch — patrols repeat, the operator does
      // not need the same alarm every 60 seconds.
      const escalationKey = `${state.id}:${deadlineMs}`;
      if (stalledReviewParentEscalations.has(escalationKey)) continue;
      stalledReviewParentEscalations.add(escalationKey);

      const paneTail = await Effect.runPromise(capturePane(state.id, 30)).catch(() => '');
      const evidence = {
        deadline: new Date(deadlineMs).toISOString(),
        reviewStatus: reviewStatus ?? 'none',
        verdictArtifact: 'none found',
        paneTail: paneTail.split('\n').filter(Boolean).slice(-5).join(' | ').slice(0, 400),
      };
      try {
        const { markWorkspaceStuck } = await import('../review-status.js');
        markWorkspaceStuck(state.issueId, 'review_parent_stalled_needs_you', {
          reason: `Review parent ${state.id} is past its review deadline with no verdict on record`,
          ...evidence,
        });
      } catch (stuckErr) {
        console.warn(`[deacon] checkStalledReviewParents: could not mark ${state.issueId} needs-you:`, stuckErr);
      }
      const message = `checkStalledReviewParents: ${state.id} past review deadline with no verdict for ${state.issueId} — escalated to operator (no kill; observability-only)`;
      actions.push(message);
      logDeaconEventSync(message);
      try {
        const { emitActivityEntrySync } = await import('../activity-logger.js');
        emitActivityEntrySync({
          source: 'review',
          level: 'warn',
          message: `Review parent for ${state.issueId} exceeded its deadline with no verdict — needs operator attention (respawn is YOUR call; the sweeper no longer kills)`,
          issueId: state.issueId,
        });
      } catch { /* activity logging is advisory */ }
    }
  } catch (error: unknown) {
    console.error('[deacon] Error checking stalled review parents:', error instanceof Error ? error.message : String(error));
  }
  return actions;
}

/** Escalation dedup for checkStalledReviewParents: `${agentId}:${deadlineMs}` keys. */
const stalledReviewParentEscalations = new Set<string>();

/**
 * PAN-3551: the verdict of record for a review run — the synthesis artifact in
 * the run's review directory (synthesis.md or review.md, via the shared
 * findVerdictReport door). Presence means the parent completed its synthesis,
 * independent of what any status plane currently claims.
 */
function hasTerminalVerdictOfRecord(state: AgentState): boolean {
  if (!state.workspace || !state.reviewRunId) return false;
  try {
    const reviewDir = join(state.workspace, '.pan', 'review', state.reviewRunId);
    return findVerdictReport(reviewDir) !== null;
  } catch {
    return false;
  }
}
