/**
 * Conversation worktrees (PAN-1533).
 *
 * Lightweight git worktrees rooted at <projectRoot>/worktrees/conv-<slug>,
 * created on demand by the conversation branch chip's "fork into worktree"
 * flow. Deliberately separate from agent workspaces under <projectRoot>/workspaces/
 * because those have a strict pipeline lifecycle (deacon patrols,
 * postMergeLifecycle, close-out) that should not touch human-driven
 * conversation worktrees.
 *
 * This service is the only path that reads/writes <projectRoot>/worktrees/.
 *
 * All I/O is async (execFile / fs.promises). No execSync, no readFileSync.
 */

import { execFile } from 'node:child_process';
import { mkdir, access } from 'node:fs/promises';
import { join, isAbsolute, normalize, relative } from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

const GIT_TIMEOUT_MS = 10_000;

/** The conventional name of the conv-worktree directory under a project root. */
export const CONV_WORKTREES_DIRNAME = 'worktrees';

/** Prefix every conv-worktree directory carries inside `worktrees/`. */
export const CONV_WORKTREE_DIR_PREFIX = 'conv-';

/**
 * Branch name format validated before passing to `git`. We accept the
 * commonly-used characters but reject paths, dot-dot escapes, and shell
 * metacharacters so the path that derives from the branch can't be
 * weaponized.
 */
const BRANCH_NAME_PATTERN = /^[a-zA-Z0-9._/-]+$/;

/**
 * Slug pattern for the directory under `worktrees/`. Generated by the
 * caller (typically from a conversation's `name` field) and validated
 * here as belt + suspenders.
 */
const SLUG_PATTERN = /^[a-zA-Z0-9_-]+$/;

export interface ConvWorktreeEntry {
  /** Absolute path on disk. */
  path: string;
  /** Branch checked out in the worktree. May differ from the directory name. */
  branch: string | null;
  /** True for the primary checkout (no worktree-specific gitdir). */
  isPrimary: boolean;
  /**
   * True when the worktree is a Panopticon-managed agent workspace
   * (lives under `workspaces/feature-*`). The conv-worktree picker uses
   * this to surface them with an "in use" indicator without offering
   * them as fork targets.
   */
  isAgentWorkspace: boolean;
  /**
   * True when the worktree is a conv-worktree (lives under `worktrees/conv-*`).
   * Mutually exclusive with `isAgentWorkspace`; both are false for the primary
   * checkout and for ad-hoc worktrees the user created by hand outside our
   * conventions.
   */
  isConvWorktree: boolean;
}

/**
 * List all worktrees of a project, classified by kind.
 *
 * Parses the porcelain output of `git worktree list --porcelain`, which
 * emits records separated by blank lines. Each record has at minimum a
 * `worktree <abs-path>` line and either `branch refs/heads/<name>` or
 * `detached`.
 */
export async function listProjectWorktrees(projectRoot: string): Promise<ConvWorktreeEntry[]> {
  const { stdout } = await execFileAsync(
    'git',
    ['-C', projectRoot, 'worktree', 'list', '--porcelain'],
    { encoding: 'utf-8', timeout: GIT_TIMEOUT_MS },
  );

  const entries: ConvWorktreeEntry[] = [];
  let currentPath: string | null = null;
  let currentBranch: string | null = null;
  let currentDetached = false;
  let currentIsBare = false;

  const flush = () => {
    if (currentPath === null) return;
    if (!currentIsBare) {
      entries.push(classifyWorktree(projectRoot, currentPath, currentBranch, currentDetached, entries.length === 0));
    }
    currentPath = null;
    currentBranch = null;
    currentDetached = false;
    currentIsBare = false;
  };

  for (const rawLine of stdout.split('\n')) {
    const line = rawLine.trim();
    if (!line) {
      flush();
      continue;
    }
    if (line.startsWith('worktree ')) {
      flush();
      currentPath = line.slice('worktree '.length).trim();
    } else if (line.startsWith('branch ')) {
      currentBranch = line.slice('branch '.length).replace(/^refs\/heads\//, '').trim();
    } else if (line === 'detached') {
      currentDetached = true;
    } else if (line === 'bare') {
      currentIsBare = true;
    }
  }
  flush();

  return entries;
}

function classifyWorktree(
  projectRoot: string,
  worktreePath: string,
  branch: string | null,
  detached: boolean,
  isFirstInList: boolean,
): ConvWorktreeEntry {
  const normalizedPath = normalize(worktreePath);
  const normalizedRoot = normalize(projectRoot);
  const isPrimary = normalizedPath === normalizedRoot || isFirstInList;

  // Classification by directory location (cheaper and more reliable than
  // grovelling .git pointer files). Agent workspaces live under
  // `workspaces/feature-*`; conv worktrees under `worktrees/conv-*`.
  const rel = relative(normalizedRoot, normalizedPath);
  const isAgentWorkspace =
    !isPrimary && rel.startsWith(`workspaces${pathSep()}feature-`);
  const isConvWorktree =
    !isPrimary && rel.startsWith(`${CONV_WORKTREES_DIRNAME}${pathSep()}${CONV_WORKTREE_DIR_PREFIX}`);

  return {
    path: normalizedPath,
    branch: detached ? null : branch,
    isPrimary,
    isAgentWorkspace,
    isConvWorktree,
  };
}

function pathSep(): string {
  // Conv worktrees only live on the host where the dashboard runs (POSIX
  // in practice — Panopticon is Linux-only). Use `/` so the relative
  // check against `git worktree list --porcelain` (which emits forward
  // slashes on POSIX) is unambiguous.
  return '/';
}

export class WorktreeValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WorktreeValidationError';
  }
}

export interface CreateConvWorktreeOptions {
  /** Project root the worktree belongs to. */
  projectRoot: string;
  /**
   * Slug used to name the directory `<projectRoot>/worktrees/conv-<slug>`.
   * Typically the source conversation's `name` (e.g. `20260526-7188`).
   */
  slug: string;
  /**
   * Branch to check out in the new worktree. If the branch doesn't exist
   * yet, it is created from `base`.
   */
  branch: string;
  /**
   * Base branch to fork from when `branch` is new. Defaults to the
   * project's primary remote-tracking branch (`origin/main`), but the
   * caller can override (e.g. to fork off `develop`).
   */
  base?: string;
}

export interface CreateConvWorktreeResult {
  path: string;
  branch: string;
  createdBranch: boolean;
}

/**
 * Create a conversation worktree at `<projectRoot>/worktrees/conv-<slug>`,
 * checking out `branch` (creating it from `base` if it doesn't exist).
 *
 * Throws `WorktreeValidationError` for any bad input. Throws plain Error
 * for git failures, with stderr in the message so callers can surface it
 * to the user.
 */
export async function createConvWorktree(
  options: CreateConvWorktreeOptions,
): Promise<CreateConvWorktreeResult> {
  const { projectRoot, slug, branch, base } = options;

  if (!isAbsolute(projectRoot)) {
    throw new WorktreeValidationError('projectRoot must be an absolute path');
  }
  if (!SLUG_PATTERN.test(slug)) {
    throw new WorktreeValidationError(
      'slug must match /^[a-zA-Z0-9_-]+$/ — got "' + slug + '"',
    );
  }
  if (!BRANCH_NAME_PATTERN.test(branch)) {
    throw new WorktreeValidationError(
      'branch name contains invalid characters — accepted: letters, digits, ./_/-',
    );
  }
  if (base !== undefined && !BRANCH_NAME_PATTERN.test(base)) {
    throw new WorktreeValidationError(
      'base branch name contains invalid characters',
    );
  }

  // Build the target path and double-check it's actually under
  // <projectRoot>/worktrees/. This is the boundary that stops a
  // malicious slug from escaping the conv-worktree convention.
  const worktreesDir = join(projectRoot, CONV_WORKTREES_DIRNAME);
  const targetPath = join(worktreesDir, `${CONV_WORKTREE_DIR_PREFIX}${slug}`);
  const rel = relative(worktreesDir, targetPath);
  if (rel.startsWith('..') || isAbsolute(rel) || rel === '') {
    throw new WorktreeValidationError(
      'computed worktree path escapes <projectRoot>/worktrees/',
    );
  }

  // Refuse to clobber an existing path.
  if (await pathExists(targetPath)) {
    throw new WorktreeValidationError(
      `worktree path already exists: ${targetPath}`,
    );
  }

  // Ensure the parent <projectRoot>/worktrees/ directory exists. Git
  // will not create it for us.
  await mkdir(worktreesDir, { recursive: true });

  // Prune any stale worktree entries from previous runs that left
  // dangling refs in .git/worktrees/.
  await execFileAsync('git', ['-C', projectRoot, 'worktree', 'prune'], {
    encoding: 'utf-8',
    timeout: GIT_TIMEOUT_MS,
  });

  // Decide whether `branch` already exists locally or remotely.
  const branchExists = await branchExistsAnywhere(projectRoot, branch);

  let createdBranch = false;
  if (branchExists) {
    await execFileAsync(
      'git',
      ['-C', projectRoot, 'worktree', 'add', targetPath, branch],
      { encoding: 'utf-8', timeout: GIT_TIMEOUT_MS },
    );
  } else {
    const baseRef = base ?? (await resolveDefaultBranch(projectRoot));
    await execFileAsync(
      'git',
      ['-C', projectRoot, 'worktree', 'add', targetPath, '-b', branch, baseRef],
      { encoding: 'utf-8', timeout: GIT_TIMEOUT_MS },
    );
    createdBranch = true;
  }

  return { path: targetPath, branch, createdBranch };
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function branchExistsAnywhere(projectRoot: string, branch: string): Promise<boolean> {
  const { stdout } = await execFileAsync(
    'git',
    ['-C', projectRoot, 'for-each-ref', '--format=%(refname:short)', `refs/heads/${branch}`, `refs/remotes/*/${branch}`],
    { encoding: 'utf-8', timeout: GIT_TIMEOUT_MS },
  ).catch(() => ({ stdout: '' }));
  return stdout.split('\n').some((line) => line.trim().length > 0);
}

/**
 * Resolve the project's default branch (typically `main` or `master`).
 * Tries `origin/HEAD` symbolic-ref first; falls back to `main` then
 * `master`. Never throws — returns `main` as the final fallback.
 */
async function resolveDefaultBranch(projectRoot: string): Promise<string> {
  try {
    const { stdout } = await execFileAsync(
      'git',
      ['-C', projectRoot, 'symbolic-ref', '--short', 'refs/remotes/origin/HEAD'],
      { encoding: 'utf-8', timeout: GIT_TIMEOUT_MS },
    );
    const trimmed = stdout.trim();
    if (trimmed.startsWith('origin/')) {
      return trimmed.slice('origin/'.length);
    }
  } catch {
    // Fall through to manual lookup.
  }
  for (const candidate of ['main', 'master']) {
    if (await branchExistsAnywhere(projectRoot, candidate)) {
      return candidate;
    }
  }
  return 'main';
}
